== Preface.

THE following pages contain extracts of letters written by three sisters,
the descendants of two ancient and honourable families,
whose rank in life had placed them in the gay world,
and furnished them with opportunities of participating in many of its more refined dissipations:
but whilst young, and esteemed accomplished,
they were strengthened to withdraw from these fascinating pleasures,
the love of Christ having touched their hearts,
the love of this world was thereby stained in their view:
thus yielding obedience to Him who called them to glory and virtue,
they had the eyes of their understandings enlightened to
behold the superior excellency there is in the Truth,
and were at seasons favoured to enjoy its enriching heavenly influence;
and as they became further dedicated, could measurably say with the Psalmist,
in the feeling language of the heart, "`The Lord is my rock and my fortress,
and my deliverer; my God, my strength, in whom I will trust; my buckler,
and the horn of my salvation, and my high tower.
For who is God, save the Lord; or who is a rock save our God?
It is God that girdeth me with strength, and maketh my way perfect.
He maketh my feet like hind`'s feet, and setteth me on high places.`"

Some lines concerning a younger sister are added at the conclusion of this volume.
