== Extracts from Elizabeth`'s Letters

Elizabeth, the eldest sister died of a consumption at Bristol Hot-Wells,
in the early part of the year 1796, at about twenty-four years of age.

She was educated in the communion of the Church of England; but not satisfied with it,
she frequented some meetings of other Christian Societies,
in the hope of finding that instruction and comfort her soul greatly desired.
She was deprived of a very affectionate father at about the age of seventeen.
A few years after one of her sisters being ill in consequence of a hurt,
was ordered to Bath, where her mother and three sisters accompanied her,
and stayed the winter.
During this period Elizabeth went to Bristol Wells to visit an aunt,
with whom she afterwards resided,
who was a religious person and had withdrawn from gay life,
and a conspicuous rank in which she was placed; as also from the established worship:
she attended different Dissenting Meeting-Houses; to one of these Eliza accompanied her;
when those words reached the witness in her mind,
"`Remember thy Creator in the days of thy youth,`" etc.

At this time she wrote the first letter to her mother at Bath,
and went thither herself after; when the sweetness of her countenance was remarkable;
she seemed a changed creature, given up and united to Him,
who in adorable mercy had not only convinced, but converted her.
She was become, not through John`'s elementary Baptism of water,
but by the one only effectual Baptism, that of the Holy Ghost and of fire;
not in words but in truth, a child of God, and an inheritor of the Kingdom of God.
When her family returned to +++_______+++,
she desired she might remain at the Wells with her aunt, which seemed extraordinary,
as a short separation was usually trying to her;
but she expressed a fear of returning to her gay acquaintance,
whilst in the infancy of religious experience, lest through weakness and instability,
she might be tried beyond her power of resistance, and so lose an immortal inheritance.
As soon as her heart was convinced that her former dress was contrary to Gospel simplicity,
she put away all the vain and superfluous parts of it,
requesting she might never be pained by seeing them.
She remained in England about two years, growing in grace and favour of the Lord.

A neglected cold fell on her lungs; her mother and sister Lucy hastened to her, and,
about two months after were witnesses to her close.
A few days before her departure, when she appeared to be asleep,
her mother remarked to her sister,
she considered it a favour that such a covering of peace was granted
them under the prospect of losing such a precious and beloved friend,
when Elizabeth raising herself, said in a lively manner, "`Peace, O Virtue,
Peace is all thy own.`"^
footnote:[Just as the spirit quitted its enfeebled tenement,
Lucy was sitting by her bedside, and the curtain being drawn between them,
she was not sensible the change was so near,
but was impressed with this language which she thought she should the have uttered,
but through diffidence withheld it, "`Open ye the everlasting gates,
and let the righteous enter in.`"--See Isaiah 26:2.]

[.centered]
==== LETTER I.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1794+++.+++

And now, my dear mother, I want to unburden my soul to you,
if I may so express myself who know as well as I,
that the ways of the world are not right, and will neither make us easy here,
or happy hereafter; but as to this you can better teach me.
What I have to say is, I am determined,
(let the world say what it will) to live according to the dictates of my conscience,
and as one who knows not the moment of death: do not, my dear mother,
by my writing more seriously than usual, think I am one bit better: indeed I am not;
I only see how long I have been upon the brink of ruin,
and wish for that content and happiness of mind which
I now believe can only be found in religion.

I know if it please God to keep me in the state of mind I am now in,
I shall enjoy more real happiness by avoiding every
place that will tend to make me forget God.
I see now that I have lived to myself; that I have been very wrong;
that if I die as I am, I must inevitably perish.
May He, who alone can make your Eliza what you would wish her to be,
and what she ought to be! etc.

[.centered]
==== LETTER II.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1794+++.+++

I am sorry to hear you are going to +++_______+++ where,
it grieves me when I think they have so much the form, without any of the power,
and inward delight,
of which religion gives the soul that resolutely
determines to seek the Lord until he is found;
as they that seek him will find him.
He waits to be gracious--when I think, my dear mother,
how long he was calling me before I answered, my heart is all gratitude;
I am astonished at his persevering goodness, that he did not leave my heart hard,
as he has done others, who would not listen to that still small voice:
for you know we read in scripture, that his "`Spirit shall not always strive with man.`"
O my dear mother! that you and I, and all that belong to us,
may be found in the narrow path, that leads to endless happiness,
is the greatest wish and constant prayer, of, etc.

[.centered]
==== LETTER III.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1794.

Many thanks to my dear mother, for the few lines concerning our best interest:
you say you wish to be as happy in your mind as i am; you will find it in Christ,
if you press for it,
if you can resolve to let go every hold that keeps
your soul fettered as it were to this world,
then read the promise that is for you in the 6th chapter of the 2nd of Corinthians,
the two last verses.
We must be convinced that we are in error,
which is very clear in the epistle of Paul to the Romans,
"`for by the law we cannot be saved; let us then fly for refuge,
and lay hold of the hope set before us; even a Saviour,
who is more ready to answer us than we are to desire it:`" Come to him,
he bids you come boldly, and do not doubt in the least, but that what he has promised,
he is able also to perform.
O that he would enlighten our minds to understand the Scriptures!

You desire me to write on the subject nearest my heart, for where our treasure is,
there will our hearts be also;
you will not then be surprised if the greatest wish I have is,
that all my dear friends would believe in the Lord Jesus Christ,
that they might be saved; but particularly that you my dear mother,
and the nearest to my heart, would implore the Lord,
and not let him go until he bless you: then you will find his ways pleasantness,
and all his paths peace;
you will enjoy a happiness the world cannot either give or take away,
and you will be of that number who are not ashamed of the Gospel of Christ,
and He will not be ashamed to confess you before his Father, and his holy angels.
I am little able to talk of the things of God;
but I trust that he who can best teach you, will answer your prayers and mine,
and enable us both to understand his divine truths.

[.centered]
==== LETTER IV.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

You say you fear you feel too little condemnation for sin: sin in ourselves,
is our greatest burden, the only obstacle that keeps our souls at a distance from God;
but blessed be his name, he first draws, encourages,
and enables the poor sinner to trust in his love,
shews him that without him he can do nothing; but when he is accepted in the Beloved,
then he is brought into the light, and sees that he is black,
as the Church expresses herself in the Canticles, 1st chap.
"`I am black, but comely,`" +++[+++in Christ]
black for the Sun of Righteousness has risen on me, and discovered to me what I am;
then is the Saviour truly precious, the chief among ten thousand, the altogether lovely;
if we knew the tenders the Saviour is willing to
make of his love to us while in this body of sin,
we should be more anxious to press on by fervent prayer, night and day:
we love to refresh our bodies when weary, but, Oh! how much more delightful,
how truly satisfying, to bathe and refresh our souls in the fountain of his love,
the streams whereof make glad the whole city of God!--His love is infinite, unsearchable,
an ocean without bottom or shore.
You say you wish to know you are born again, and the next line tells me that you are,
by saying, that you will be ever with that dear Lord that has all your affections.
I wonder how you would explain those words; for my part I think it is being born again,
born of the Spirit, when we can from our hearts say, he has all our affections,
"`Jesus`' love has broke my heart:`" the natural man is
enmity against God,--I once saw no comeliness in him,
but now all is vanity but Christ: we can say,
"`What is all the earth to me if stranger to thy peace?`"
The knowledge of these truths only, is not enough;
it is only so far as they are felt and experienced in the mind of a believer,
that they communicate peace and happiness to the soul.

[.centered]
==== LETTER V.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

The two dear girls`' letters delighted me:
what a favour to have so many in a family candidates for heaven!
Dear mother, you and Lucy are wanting some strong earnest that you are children of God:
think for a moment that you love him who has died for you;
don`'t you depend entirely upon him?
Remember you love him because he first loved you: let us but believe,
and we shall find him precious.

[.centered]
==== LETTER VI.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

Dear mother, what need have we to pray, that we may be disengaged from this world,
and the nearest friends we have in it: if my mother, my aunt +++[+++then ill]
and my Lucy are taken from me, I have not a tie besides.
May my Lord resign me to his will!
Of myself I can do nothing, I must trust him;
and indeed at this time of trial he sweetly supports
and comforts my heart and spirit with his love:
all these things must pass away, but who or what can separate from Him our souls`' love?
My aunt is a little better this day than yesterday;
who knows but our compassionate Lord will again restore her health,
most valuable to those who know her best,

[.centered]
==== LETTER VII.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

My dear mother, i have shed tears of joy over your letter;
may our hearts be filled with gratitude and thankfulness,
that while we were living without hope, and without God in the world,
we are brought into the light of the glorious gospel,
and called to partake of the blessings our saviour has purchased for us;
and that it is evident not for the smallest good in us,
because his pure eyes see our manifold infirmities, but of his infinite mercy;
and a kingdom has been prepared for such as resist not his power,
before the foundations of the world.

My dear mother, I do not think you are deceived;
nothing but the love of Jesus can spoil us for this world;
his love constrainseth us to follow him through evil as through good report;
he loved us before we loved him,
and can we doubt of his love one moment when we think and
read of his great sufferings for your and my sins,
and of all who are willing to be saved?
O let us try to get above this ensnaring world;
our dear Lord will enable us through faith to overcome it,
if we perseveringly go on trusting in him for strength,
knowing only such as persevere to the end shall be saved: and, indeed,
I cannot see this world has any attractions for those who live as always in his sight,
enjoying the smiles of his reconciled countenance,
and feasting on the bounties of his love.
I have learned that Jesus loves +++[+++that]
we should tell him all our wants, and he loves to supply them.
O what a privilege! we need only leave our petitions with him, and trust in his promises;
but then we must through his assistance, conform our lives to his will,
or it would be foolish to expect a blessing: I desire to be entirely moulded to his mind;
for I am his, and nothing can separate unworthy me from his love.
And will my sweet Lucy and Judith come and partake of that good part Mary chose,
which never can be taken away?
The very thought and hope delights me, that when a few years are past,
we shall all be in the enjoyment of unutterable bliss.
I must leave room for my dear aunt to add a line,
with just leaving you one comfortable thought, that if the world hate you,
it hated our dear Lord first; he says in John,
because "`I have chosen you out of the world,`" etc. and
left us an example that we should follow his steps.

[.centered]
==== LETTER VIII.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

Nothing but grace will effectually turn the heart; till then all is restraint.
I wish you would send +++_______+++ to the Wells.
O that his heart might be touched;
(at present he cannot be happy,) I think he would
be a burning and shining light:--My dear mother,
I trust you will not be displeased that I caution you against
sending Judith to +++_______+++. I know she is a sweet creature,
and with your example and instruction may be an excellent Christian;
but she is human nature still, and I fear with those she will mix with,
these good impressions will soon be effaced:
in one night a tender plant may be lost by a severe frost.
Our dear Lord knowing our poor weak nature well, prayed, +++[+++taught us to pray]
that we might not be led into temptation.
O may he direct you and me in every step we take, though ever so trifling;
may he also continue to keep your mind peaceable and happy!
The effect of being clothed in his righteousness is quietness and assurance forever.
What a sweet passage! "`mercy shall compass him about;`"
all your afflictions come through mercy:
the Lord is a wall of fire round about his people, a very present help in trouble.
What a great comfort that we are kept by the power of God through faith unto salvation.
If I was not an ungrateful creature,
I should make mention of the lovingkindness of the Lord from day to day; he directs,
encourages, and instructs me with his love,
"`he is altogether lovely:`" he will withhold nothing
from you that may do you good if you ask it.
May you enjoy communion with our dear Lord, which is the privilege of all true believers,
and which they would not give up for all a thousand worlds could offer:
for surely heaven has more happiness for an immortal soul than earth.--In the 17th of
Jeremiah I read this morning the curse that was to befall those that forsook God,
was, their names were written in the earth; O that ours may be written in heaven!

[.centered]
==== LETTER IX.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
1795.

I was greatly delighted with my dear Judith`'s letter: you have found a precious saviour,
the pearl of great price, and the angels in heaven rejoice over you;
the saviour loves you with an everlasting love,
he will shew you what is in your own heart, that you may prize him more;
at least i find he shews me every day my own nothingness, that being emptied of self,
i may look only to Christ for a full and free salvation:
it is not of works lest any should boast; but by grace we are saved through faith,
which is the unmerited gift of God:
there are unspeakable riches treasured up in Christ for us.
O may we daily be enabled to come boldly as dear children,
and receive out of his inexhaustible fullness of grace and love,
that we may grow up into him in all things: may he teach us how to live, think,
act and speak for him who has done so much for us!

My dear mother writes to me, +++_______+++ is coming: I expect him every moment.
O my dear Judith, join with me in intreating our dear Saviour, to be his Saviour,
and that he may be one of those jewels that make up his crown!
I have time for no more, but to commit you to his care, who has loved you,
and given himself for you; may he direct you and keep you,
giving you strength for every trial; may his love prevent every discouragement,
and be an earnest to you of future glory, etc.

[.centered]
==== LETTER X.

[.letter-heading]
To her Mother.

[.signed-section-context-open]
1795.

I look forward with pleasure to seeing my dear +++_______+++ after so long an absence,
though I am sure I do not think he will be so pleased with me.
However the Lord is on my side, I will not fear; who knows, my dear mother,
but his coming here may be for the better: when I think what has been done for me,
I believe nothing is too hard for the Lord; our united petitions will be heard +++[+++if right]
by him whose name is love, and who has no pleasure in the spiritual death of any.
I am sorry for +++_______+++`'s behaviour, but we know it is nothing new;
we have many to intreat the Lord for.

You say you are thankful for your illness at +++_______+++,
therefore it is not right I should be sorry,
but trust the Lord will restore your health of body, and keep your soul in health.

I have been twice to see +++_______+++, will not that do?
They were very curious,
but I trust my dear Saviour will never suffer me to be ashamed of him:
they wondered I did not go to balls; "`don`'t you go to any parties?`"
If you mean card parties, I said, I do not at all approve of them,
but my aunt and I have very agreeable parties amongst
some of the most respectable people here.
My dear mother, I know very well, (I should say I know a little) of what you mean,
when you speak of the corruption and ingratitude of the heart.
I will give you a hint of a dream I had the night before last,
which may be of use and comforting: "`Live out of yourself,
simply by faith on Jesus Christ,
laying your sins and sorrows upon him;`" a few words but very comprehensive;
let us then look to him; it is only while we live upon Christ, we live at all;
don`'t you find you cannot mix with the people about you?
You cannot drink muddy water and sweet together; it is precious to live near the Saviour:
in his presence is fulness of joy!
Oh, when will the time come when we shall be in the enjoyment of him;
when we shall see him face to face, then will our cup be full, running over!

[.centered]
==== LETTER XI.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

I rejoice that you are enabled to stem the torrent of persecution by and through Jesus,
who will +++[+++would]
bring you, through toiling and rowing, to land in his Father`'s kingdom,
beyond the reach of men and devils, to enjoy himself, which must be heaven indeed.
O may he give us to taste more while here of his hidden manna;
that continually receiving from his fulness,
we may have that which will cause us to glorify him.
I find my soul is dead indeed, if my Beloved withdraws;
or rather when the curtain is drawn over my soul:

[verse]
____
"`He is our life, our light, our love,
Our portion, and our all,
The circle where my passions move
And centre of my soul.`"
____

You are the persons our Lord has himself pronounced blessed;
he bids you rejoice and be exceeding glad.
May we be vigilant to serve our Master, and pray for them that hate us!
I want nothing but what my Jesus has to give, and he is always willing,
and we might be always receiving,
if unbelief did not prevent us opening wide the door of our hearts,
that he might come in and sup with us according to his promise.--I
think he is teaching me more every day,
there is nothing worth having but himself, nor enjoying,
but as we receive in it something of his love: don`'t you find it so?
If we have him, we have more than tongue can describe, we have sweet peace within,
that we enjoy by looking in faith through our interceding Saviour to our loving Father.
What mere earthen vessels we are, empty and liable to be broken:
what a blessing to see we are so, that we may ask and receive, and be filled;
that we may come up from this wilderness leaning on our Beloved!
He will hold us up, and we shall be safe.
But I must stop and recollect, this subject of a soul`'s love would fill my paper,
and after all, I have said nothing: I must leave the subject to eternity,
we can`'t comprehend, much less talk of it, though to feel it is heaven begun!
And does my sweet Lucy give her idols to the moles and the bats: this is love again!

Tell +++_______+++ if you have no objection that (from
my soul) I wish she was what they call a Quaker,
but that most of all, I wish her to be a Christian;
a despised follower of a despised Saviour.
I have acquitted my conscience already, and tell her from me, if she reject this Saviour,
He will reject her,
and the horrible consequence no pen can paint.--Need I tell my beloved parent
my heart is united to her`'s forever in love by the strongest bands.

[.postscript]
====

P+++.+++ S. When you give my message give it in love: there is great harmony in love.

====

[.centered]
==== LETTER XII.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

To those who find religion a real good, retirement is delightful,
as it enables us without interruption to seek for peace,
and to enjoy the greatest privileges:
communion with him who condescends to be the Friend of sinners,
and rejoices over them to do them good.

O may we unfeignedly give him all our hearts, and commit the keeping of our souls to him,
who is able to keep them until that great day, when our Saviour,
who manifests his love to us, will be our Judge:
He who now intercedes for us.--We are reading an account of the
numbers of martyrs that died in the flames in Mary`'s reign,
all rejoicing they were counted worthy to suffer for the truth; let this encourage us,
my dear mother, not to mind what the world may say:
those will one day be ashamed that falsely accuse your good conversation in Christ;
and remember for your comfort, your light afflictions, which are but for a moment,
work for you an eternal weight of glory.
My two sweet sisters are afraid of the temptations of the world;
and since I have set them the example of mixing in it, it is but fair to tell them,
I never knew happiness in the pleasures of it: they are toilsome and unsatisfying;
assure them with my love, were I to begin the world again,
I would seek to walk in wisdom`'s ways, they are ways of pleasantness,
and all her paths are peace.

[.centered]
==== LETTER XIII.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

When we think on what a slender thread life hangs,
not to have an interest in Christ is most awful!
To you who believe he is precious, these are sweet words,
"`Christ in you the hope of glory.`"
O for a stronger faith to rest entirely on his unchangeable love,
an abiding sense of which would sweeten every cross and create a heaven within.

[.centered]
==== LETTER XIV.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

I hope you will inform me of your health, and the state of your soul,
which I doubt not is soaring on the wings of love,
and every day getting nearer and nearer in sweet communion with the Friend of sinners;
those are the most delightful moments of one`'s life:
by Lucy`'s and Judith`'s letters they seem indeed on the road,
as they desire those evidences which, if they persevere, they will certainly receive;
from experience I know they will have the inward witness, they are the children of God,
and of course,
all things will work together for good both here
and hereafter.--Blessed indeed are the heirs of God,
joint heirs with Christ! how different from the world in pursuit of happiness,
who try many different ways for present enjoyment and recreations,
and still are dissatisfied, finding only disappointment;
while Christians have all one motive, one joy, one Saviour, and I would wish,
one mind! all pressing towards the same mark, our dear Lord going all the way with them.
O may we continue steadfast in the faith,
and never be discouraged by the insinuations of the enemy,
who would work "`with our poor weak hearts: but we have this delightful promise,
"`Resist the devil and he will flee.`"

[.centered]
==== LETTER XV.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

When I think of what darkness and unbelief there is over the world,
it fills me with horror.
I tremble to think of +++_______+++ who do not see their want of a Saviour,
and the wicked one will keep them blind as long as he can.
O my dear mother,
what reason have you and I to be thankful that we see we cannot save ourselves;
that our righteousness is but as filthy rags;
what a blessing to see the vileness of our hearts,
that they are deceitful above all things,
when we know the returning sinner will be accepted and pardoned for Christ`'s sake.
I often think, if those that are in the midst of pleasure and dissipation,
did but for a moment feel the joy of a believer,
with what astonishment would they look back on their past choice!
I do firmly believe they would go and sell all that they had,
and purchase that pearl of great price.

[.centered]
==== LETTER XVI.

[.letter-heading]
To Her Mother and Sister Lucy.

[.signed-section-context-open]
1795.

Thanks to my dear Mother and Lucy for their joint letter:
indeed I want words to express the true delight I felt on reading it.
Is it not some of that love which the members of Jesus must feel for each other?
He is all love, and the sap which belongs to the Vine, suffuses through all the branches:
as many as are led by the Spirit of God, they are the sons of God,
and sweet teaching it is; we love what he loves, and hate what he hates,
so that we know the meaning of those words, He that is joined to the Lord in one spirit,
he has, though in a lesser degree, the mind of Christ.

This month reminds me of the happy moments when I began to live:
when we reflect what creatures we are by nature, divested of all good,
and prone to evil continually, every moment adding sin to sin,
until there is a list against us,
which nothing but the blood of Jesus himself could do away,
that he not only freely pardons us, but takes and carries us in his bosom,
and gives us all things in himself; clothes us in white,
and gives us to live upon himself, food convenient for us, and living waters,
so that we do not thirst for perishing things:
when we consider that our hearts are drawn above, where we shall be in a few years,
it is enough to sink us into nothing but love before him.--I
have been much afflicted for months with pains in my jaw,
but was much supported, as you are, by the presence of him our souls love,
and we shall have this peace while our minds are stayed upon him.
What poor bodies we have: O may our souls get more life,
then we shall think less of the body`'s death.

My dear Lucy`'s letter quite warmed my heart, and truly filled me with joy;
nothing indeed but the power of God could change our hearts:
may he enable us to persevere, until we receive the end of our faith,
which is the salvation of our souls.
Meditating on future enjoyments greatly alleviates present distress:
though persecutions for the present are grievous, yet they yield,
the peaceable fruits of righteousness to you who are exercised thereby;
and though "`the bud may have a bitter taste,
yet sweet will be the flower,`" only let us follow on to know the Lord.

My dear mother, may the Lord return all your love to me, unworthy me,
into your own bosom: he loves you better than I can,
and I am happy in believing you are in his hands,
who will keep you as the apple of his eye.
Farewell my dear beloved parent, and my sweet Lucy,
I bear you on my heart before my dear Redeemer; but what is better,
He bears your name himself before the throne.

[.signed-section-closing]
Your`'s in the sweet bonds of Jesus.

[.centered]
==== LETTER XVII.

[.letter-heading]
To her Mother.

[.signed-section-context-open]
1795.

I am obliged to my dear Lucy for her elegant work:
may her dear heart and ours be stamped with the image of Jesus,
as the paper is pricked into an Edwin and Angelina;
our hearts were as much a blank to any good impression, as that paper was,
but our Artist is divine, both God and man!
O may he keep you, my dear mother, from error,
and give you the teachings of his good Spirit,
which always testifies of Jesus our Advocate,
in whom dwells all the fulness of the Godhead bodily;
and though it is most delightful to walk in the comforts of the Holy Spirit,
yet we must not forget from whence they flow;
that they have been dearly purchased for us by Christ;
are the effects of the Father`'s love given us through the agency of his blessed Spirit.
Oh! what manner of love is this that our God has taken upon
him in this wonderful manner to save poor sinners,
and that he stands engaged in covenant for their good by these three offices, of Father,
Saviour, and Comforter!
O may the Spirit of truth lead you into all truth.
Jesus says, "`I am the way, the truth, and the life.`"
I am sorry for the account of your poor health:
what can be dearer to my heart than my dear mother`'s spiritual and temporal health?
O may He, who alone is dearer, give you both,
and if best for you he will give you health:
all his dealings with you are in love infinite, unchangeable: may he give you and me,
in the darkest hour of his providence, to see it so,
that we may like Sampson get honey out of the lion`'s carcase.

[.centered]
==== LETTER XVIII.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
1795.

My dear mother, I am not prejudiced against any sect; indeed I am not:
my Lord has enabled me to love all that have the mark of the Lamb on their foreheads;
all that love the Lord Jesus, must have been first loved by him:
and shall I not love those whom Jesus loves, brethren and sisters for whom Christ died,
all one happy family whose names are written on Emanuel`'s bosom?
O yes! my heart warms to them, and would bring others if I could, to join them;
but human means, are only means; but he says, if ye love me, keep my commandments,
we shew our faith by our works, the very thought is sufficient to make me blush,
I do so little; your letters shew the sweet frame of your mind,
and my dear Saviour has promised to keep him in perfect peace,
whose mind is stayed on him, and I trust he will bring you to his banqueting house,
and his banner over you will be love.

Tell my dear Lucy, I am obliged for her elegant work.
I have seen several pieces from Italy, and I think her`'s preferable,
I send her something, though in a different way, but before she looks at it,
I request her to read a few lines I send with it: the worst of these amusements is,
they engage too much time and thought; while our hands are at work, we should endeavour,
at the same time, to delight our hearts in thinking of the love that bought us.

[.centered]
==== LETTER XIX.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
March 31, 1795.

What soul can be truly happy until in the perfect enjoyment of its Saviour?
I have no idea of any thing here deserving the name of happiness but what faith realizes;
only so far as we live upon the fulness of Jesus we live at all;
for don`'t we find there is a spiritual, as well as natural life?
All have not the former, only believers in Jesus; these know what the hidden manna means,
which is the life of their souls, this tree of life, of which they eat and live forever.
Don`'t think me prejudiced, my dear mother, for or against any sect;
my heart does feel a sympathy to all of every denomination that love the Lord Jesus;
those that live nearest him, live nearest the truth:
some of all professions are apt to get into a cold, formal state,
there is nothing I so much dread for myself as this:
may our dear Lord keep us alive and zealous for his glory, having our lamps lighted;
and to his dear name be all the glory and praise!

My beloved mother,
you cannot think what sweet subjects you are at times of my thankfulness,
that you and those nearest my heart are heirs of glory; and shall I too be admitted?
What mercy, what unutterable love!
O how many sweet creatures there are that have not the mark of the Lamb:
may we be humble and thankful.
I often think of dear +++_______+++, you remember he always was my favourite,
perhaps from his name and likeness to one I love,
and whose memory will ever be dear to me.^
footnote:[Alluding to her father.]
Farewell;
may you have the presence of Jesus to support and
comfort you in all your trials and bitter cups,
my dear mother, whom I love in the truth.

[.centered]
==== LETTER XX.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
May 30, 1796.^
footnote:[A few months prior to the date of this letter,
Mary Dudley, a beloved minister in the Society of Friends,
recorded the following passage in her journal:
{footnote-paragraph-split}
"`I continue to feel my mind attracted to several who attend our meetings with honest inquiries,
'`what shall we do?`' etc.
Among these are a family, respecting whom I had no knowledge or information;
but while in meeting the day after I came here,
my heart was drawn into such a feeling of secret sympathy with two genteel looking women
who sat solidly opposite the gallery, that I was ready to marvel,
not knowing by their appearance whether they had any connection with Friends or not.
At length I became so exercised, that the work in them might be carried forward,
and the new creation perfected, that vocal supplication was offered,
and inquiring after meeting respecting them,
I found they were a widow Ussher and her daughter,
and that they had constantly attended meetings for several months past.
I spoke to them on going out of the meeting house, and they cordially to me;
since then we have seen more of each other;
they are indeed a wonderful family, and the more I know of them,
the more my heart is attached to them.`"]

My ever dear mother has already received accounts of my illness;
the means used have been instrumental to my recovery,
through him who knows how unfit my soul is for glory.
O may he hasten to prepare me for himself!
Nothing short of the enjoyment of God can satisfy, when he in infinite condescension,
shews even a little of the love he feels for poor worms; though he afflicts,
yet still he loves the same, it is because he loves he chastens:
my sickness has been so sweetened, and his presence so comforted me,
as brought to my mind a verse, I believe in Hosea, where it is said,
"`I will allure her and bring her into the wilderness,
and speak comfortably to her,`" +++[+++to the Church]
after mentioning her great sins.--O what a God full of love is our God:
the more fully we believe in his love, the greater is our happiness.

My cough is indifferent: it will be a comfort to hear from my dear mother,
I cannot think of you but my heart glows with love for you,
and longing desires to see you; but this, together with yourself,
and everything else that relates to us, I commit to him who alone does all things well:
it is with difficulty I have written;
may every blessing from our loving Jesus be with you all.

[.centered]
==== LETTER XXI.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
June 16, 1796.

My darling mother, my last not being satisfactory as to my health,
I sit down quietly to tell you, I am better this day than yesterday.
I am very changeable, not like my precious Lord, whose love continues every day alike.
I cannot say, from my feelings, or my physicians`' authority, that I am getting better,
though some days more comfortable.
My dear mother, if you love me, don`'t be grieved for my illness:
sure you don`'t love my body better than my soul;
the latter has been taught many sweet lessons by it;
it is only on your account I suffer any anxiety,
being the means of adding sorrow to sorrow; besides you, and my dear family,
I have not a tie to anything below, though I don`'t know that I am in present danger,
yet I cannot conceal the pleasure my soul feels in knowing I am in my Saviour`'s
hands to do what he will with me.--If we but meditate on future joys,
all which flow from the infinite fulness of Jesus filling the soul,
and increasing it every moment with delight,
such as we cannot fully know till we are in the enjoyment of it, who would wish to stay?

[verse]
____
"`May we have patience here to wait,
Till Jesus us to bliss translate.`"
____

I own I would wish you to come here if you would not be distressed by it:
surely it is a selfish wish to see her who lies nearest my heart of all earthly attachments,
but I now give up the hope,
preferring your comfort to everything in this world.--My dear mother, mind,
we are all in his hands, who will make us more than conquerors through him that loved us.
