== Extracts From Lucy`'s Letters

Lucy, the second sister was taken ill of a consumption
and died the latter part of the year 1797,
aged about twenty-one years.

She was very pleasing in her person, of a meek spirit, and religiously thoughtful,
yet partook of what she, at that time, deemed innocent recreations,
and in the way she was educated, what were esteemed polite accomplishments,
such as music, dancing, painting, etc.; but as she became convinced,
that to purchase the pearl of great price we must sell all that is vain and superfluous,
all that divides and separates the heart from the one great and only good;
she relinquished these inferior pursuits,
which faded as shadows at the rising of the Sun of Righteousness in her soul.

She was dissatisfied with the forms and repetitions of the established worship,
and longed for right direction to worship God in spirit and in truth.

About this time she became acquainted with some of the Society of Friends,
and with her mother, accompanied them to their meeting: when in silence, that is,
outward silence,
she was convinced that Friends were united in the one precious principle;
and these words were intelligibly sounded in her spiritual ear,
"`Join thyself to these people,`" which divine intimation she readily obeyed,
and submitting to the yoke of Christ,
she cheerfully endured the refining power that was to judge
everything her dear Lord`'s controversy was with,
and nail it to the cross.
At this time these words were frequently impressed on her mind,
"`The valley of Achor shall be the door of hope;`" not remembering such words,
she took her bible and opened it at that passage,
and found it was there the Babylonish garment was to be burned:
she consulted not with flesh and blood, but set fire to all her fine clothes,
a great part of which were her own work, and beautiful,
besides others that had been bought; she left none of gold, or silver, or costly array,
making of them a fire sufficient to warm water to wash her hands.
The peace of her countenance afterwards evinced,
that the sacrifice required was accepted,
and the outward purification seemed emblematical of the purity of her mind.
She had strong and lively feelings,
and though young in years was deeply taught by uncommon baptisms,
tending to her further refinement.

Her sister Judith took notes concerning her after she had taken to her bed,
of the illness of which she died, from which the following is extracted:

[.embedded-content-document.testimony]
--

She had been for some time deeply exercised,
but at this season her mind seemed to be sweetly relieved, and covered with divine love,
which flowed to all around her.
She called me to her, and said, the way before her was dark,
and she knew not whether to look for life or death, but was resigned to the event,
saying, she believed if it was the Lord`'s will to take her, it would be to himself;
expressing in much tenderness of spirit, that if her life was prolonged,
she hoped it would be entirely dedicated to His service,
for what else was worth living for?
and with great earnestness expressed her desires that I should be faithful unto the Lord,
and not withhold anything he may require;
likewise that she had often felt much interested for me,
and had received this comfortable impression,
that the Lord would give me change of raiment.
One evening being so ill as to think she could not hold out long,
and getting me to sit by the side of her bed,
she gave some directions about the disposal of her property,
and with her love given to her sister Susan and her dear brother John,
she desired (as near as I can recollect) they would keep much inward to the Lord,
who would direct them.
I cannot remember all she said at that time,
being much tendered and enlarged by the overflowings of divine love.
She expressed great resignation to whatsoever was the Lord`'s holy will concerning her;
adding, "`Though He slay me yet will I trust in him,`" and said,
she thought she felt resignation in me also,
in which I was wonderfully supported about that time,
for though I did not think I could love her better, yet such were my feelings,
that had the Lord demanded it,
it seemed as if I could part with all that was near and dear to me in this life,
in acquiescence to his will.

A few days before dear Lucy`'s departure she called to her mother and said,
she remembered in a particular manner,
what a powerful impression the last testimony of
Mary Ridgway`'s that she heard at meeting,
had on her mind; that it seemed to have passed away, but then revived,
and she felt easy to repeat so much:
"`Ye are they that have been with me in my trials and in my temptations,
and for you my Father has prepared a crown of glory
that fadeth not away.`" At another time she said,
"`Oh! what an awful thing to appear before a God
of purity!`" Her bodily pains seemed excessive,
yet she never complained, but with a sweet countenance, often said,
"`It is not of any consequence, if it does the work of purification it is a favor.`"

She said she remembered at the only meeting for discipline that she sat,
an Epistle was read, where after much encouragement was expressed to the young,
there was added a desire for those who should be cut off in their bloom,
that their conduct and example might be such that would leave a savour behind;
and at the same time she believed she was of the number that was to be removed,
and did ardently crave that the latter part might be applicable to herself.

--

She was admitted into membership with the society
of Friends about a year and half before her decease.

[.centered]
=== LETTER I.

[.letter-heading]
To her Sister Elizabeth.

[.signed-section-context-open]
April 20, 1795.

Since I wrote last to my dear Eliza,
we have enjoyed a delightful season of spiritual refreshment,
in which the great Shepherd has been pleased to send us pastors after his own heart,
who have rightly divided unto us the words of life,
and administered to us freely what they had freely received from Him,
according to our several cases and necessities.
May we be totally devoted and given up to Him,
and count nothing too dear to part with for his sake,
who remembered us in our low estate,
and has called us out of darkness into his marvellous light,
and has guided our feet into the paths of true peace!

You will, I fear, think those ministers were informed of our situations,
and spoke from outward knowledge, but be assured it was not the case,
no person could tell them our thoughts: O no,
they have their knowledge the same way that Peter knew that Jesus was the Christ,
for which our Lord pronounced him blessed in those words,
'`Blessed art thou Simon Barjona, for flesh and blood hath not revealed this unto thee,
but my Father who is in heaven,
for upon this rock (even revelation) will I build my church,
and the gates of hell shall not prevail against it.`' Paul
also in his first epistle to the Galatians fully shews,
that the gospel which he preached he received not of man,
nor was he taught but by the revelation of the Lord Jesus,
surely he could not have meant the outward appearing of the Lord Jesus by the way,
that might have converted him from the errors in which he then was,
and have opened his eyes and his heart to receive
and see Him in his far more glorious appearance,
even that true light that enlighteneth every man; this glorious privilege,
is not confined to apostles or ministers,
but he vouchsafes to teach all his depending children who come
to his school with hearts emptied of self and self-righteousness,
and under the humbling feeling, that without Him they can do nothing;
and therefore give themselves up into his forming hand,
to be made either vessels of honor or dishonor, in his holy house;
so that He will but sanctify them for the Master`'s use.

O may we not shrink, my dear Eliza, but Follow the Captain of our salvation,
who was made perfect through sufferings;
who though He thought it no robbery to be equal with God,
yet took upon Him the form of a servant, and became of no reputation,
humbled himself unto death, even the death of the cross!
May I, the least and most unworthy of all his creatures,
who am not meet to be called a disciple, take up my cross daily,
and deny myself everything that I feel contrary to the mind of my gracious Master:
for I do believe the cross is much harder to be borne
in little things (if they can be called so,
when they separate us from Him who is the chief among ten thousand and altogether
lovely) than in those things which are evidently wrong to all sorts of Christians;
it is dreadful to our natural part to appear singular in dress or language,
yet I believe it must be your Lucy`'s lot if she follow the path pointed out to her,
as I believe it is required of me to bear a testimony for truth,
and to magnify my Saviour openly;
not that any thing I can do of myself can be acceptable in His sight;
for if I should do all, I should be but an unprofitable servant:
but I trust he will work in me both to will and to do,
and to Him shall be the honor and the praise forever.
It grieves me to hear of my aunt`'s indisposition:
were you not with her I know not what she would do;
you must certainly be a great comfort to her in her present situation,
stretched upon a bed of languishing,
but I trust the great Physician who has laid her on it,
stands by her and gives her the oil of joy for mourning,
and the garments of praise for the spirit of heaviness,
and that the present dispensation will tend to brighten her,
and that she will come forth as gold seven times tried,
and as a corner stone polished after the similitude of a palace:
assure her of my most affectionate duty and love.

My grandfather and grandmother are reconciled to
our going to meeting and leaving the public worship,
and appear as affectionate as ever to us,
so fully has that promise been fulfilled which has been often sealed to me,
"`I will make darkness light before thee, and crooked things straight,
these things will I do unto thee, and not forsake thee.`"

To him who has hitherto preserved you my dearest Eliza, I recommend you:
may He still watch over you for good, and may you, under his divine care, grow in grace,
and go on unto perfection,
until you attain unto the measure of the stature of the fulness of Christ,
and be daily weaned from instruments, till He shall be your all in all,
is the breathing of my soul for you, etc.

[.centered]
=== LETTER II.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
August 28, 1795.

I thank you my dearest Judith, for your best of wishes: indeed it is impious to doubt,
what did our beloved Lord die for, if not to save us from sin;
which is the only thing that can separate us from
those blessings which eye hath not seen or ear heard, etc.
What a happy day will that be when this body of sin shall be destroyed,
and we shall be admitted into the glorious liberty of the children of God!
I trust I shall be delivered in his own good time from all my enemies,
and that I reckon my greatest.
There is nothing too hard for the Lord,
we cannot ask too much or more than he is willing to give:--let
us then come boldly to the throne of grace,
that we may obtain mercy and find grace to help in time of need; and may you and I,
my love,
be among those happy few who shall unto all eternity
follow the Lamb whithersoever he goeth;
and shall wash our robes and make them white, in his most precious blood.

[.centered]
=== LETTER III.

[.letter-heading]
To her Sister Judith

[.signed-section-context-open]
1795.

You are not as happy as I could wish in your present situation,
but you must try to reconcile yourself to a short separation,
knowing that you have the best of parents always with you,
who has promised that you shall not be tempted above what you are able to bear, but will,
with the temptation, make a way to escape, that you may be able to bear it.
Another delightful idea is, that "`By grace ye are saved, and that not of yourselves,
it is the gift of God:`" so you see we are kept by the power of God,
through faith unto salvation.
Have you not encouragement to submit (as I am sure you do) your temporal,
as well as your everlasting happiness into the hands of Him who careth for you.

[.centered]
=== LETTER IV.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
Sept. 9, 1795.

What a happy spirit that is which dear Eliza was directed to in
a dream! to look simply to our beloved Lord in everything,
not to ourselves or our own works; if we fall, to lean upon him to rise again,
knowing and depending on His strength: though we fall we shall not be utterly cast down,
for the Lord upholdeth us with his hand.

What wonderful kindness has he bestowed upon me, blessed be His name,
that my many falls and yieldings to temptations did
not provoke him to cast me off forever,
but has brought me here, where without a church, without a minister, or ordinances,^
footnote:[Alluding to the Church, as by law established.]
I have felt more peace than ever I did before;
it would be the highest ingratitude not to acknowledge the debt I owe Him,
the giver of every good and every perfect gift: May I, in the whole course of my life,
be it long or short, live to his glory, and never grieve his Holy Spirit,
as I have done continually!
What a shocking thing to see so many running on in the broad way to everlasting destruction,
who at the same time think themselves perfectly safe, expecting the mercy of God,
without considering we can build on no other foundation than that which is already laid,
even his Son Jesus Christ.
Have you read Cowper`'s Poems?
they are wrote in the spirit of Christianity;
I cannot forbear giving you a sample of them:

[verse]
____
"`A soul redeem`'d demands a life of praise,
Hence the complexion of his future days;
Hence a demeanor holy and unspeck`'d,
And the world`'s hatred as its sure effect.`"
____

[.centered]
=== LETTER V.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
Sept. 25, 1795.

Our dear +++_______+++ expects soon to sail for Gibraltar.
In his way through Bristol he spent a little time with Eliza,
who took him to hear a gospel minister,
who I have no doubt said something adapted to his state.
Who knows when it may occur to his mind with double force?
And though the seed may be for a short time hid, and, as it were,
a grain of mustard seed, it may yet take the deeper root, and bring forth the more fruit,
to the glory of our dear Saviour,
who came not to call the righteous but sinners to repentance.
And should we not be the most ungrateful creatures in the world,
did we not love and delight to serve our dear Lord,
who has been so kind as to call us when we were rebels and enemies; to call us to what?
To be heirs with God, and joint heirs with Christ!
And when called by Him, why not follow Him through evil, as through good report?
Oh that we may never draw back, nor be of that unhappy number in whom He has no pleasure!

[.centered]
=== LETTER VI.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
1795.

I congratulate my beloved Judith upon her safe arrival at +++_______+++,
and trust the journey and change of air will be of use to you,
but indeed bodily exercise profiteth little, but godliness is profitable for all things,
having the promise of this life and that which is to come.
I am more and more convinced every day, that all the illness I suffered at Bath,
and last winter, was through divine mercy to keep me from the vain and giddy world;
and though I did not feel much attachment, yet I was ashamed to take up the cross,
and dare to be singular;
but glory to Him who has in some degree enabled me to come forth from the wilderness,
leaning upon my beloved.
O may I never again doubt, but cast all my care upon Him who careth for me,
and never fear the cross; for He has promised,
He will make the yoke easy and the burden light;
He alone can and will sweeten the bitter cup of adversity:
He has promised that if we acknowledge him in all our ways, He will direct our paths,
He will be our guide unto death, and after death our portion and happiness everlasting:
O may we never stray from such a Shepherd, who gathers the lambs in his arms,
and gently leads those that are with young.
May you and I, my dear Judith, ever remain in the enclosed garden of the church,
ready to answer the slightest call,
even as the putting forth of the Beloved`'s finger through the hole of the door,
let the way be ever so narrow or contrary to flesh and blood;
and as our bodies are the temple of the Holy Ghost, may we seek direction from Him,
knowing that in his own time He will be found of them that diligently seek him.

You did not answer that part of my letter upon waiting
in silence upon the Lord for divine teaching,
which was a disappointment to me,
as from that I have more real comfort than ever I had through the medium of another;
I wish every one to know and practice it,
there is no other way in which self is so humbled,
for it is only in the silence of all that is fleshly,
that the small still voice is to be heard;
even when walking or working you may retire inward
and enjoy sweet communion with the Lord;
and it is not, Lo here, or lo there, for the word (Jesus Christ) is in thy mouth,
and in thy heart.
My mother had a letter from dear +++_______+++. I feel
happy in having fulfilled my duty by writing to him,
and having told him all my mind, which letter he acknowledged,
and said he was very much obliged to me for my good advice.
Oh, may the Lord be his preserver, and enable us to submit to his divine will,
knowing that whatsoever is by His appointment is best.
May we all meet round the throne of the Lamb, where no enemy can assault,
nor snare allure, where this corruptible shall put on incorruption,
and this mortal immortality, etc.

[.centered]
=== LETTER VII.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
Nov. 14, 1795.

I am sure it will give my dear Judith pleasure to hear of the safe arrival of dear +++_______+++:
thanks be to Him who has preserved him and brought him through
so many dangerous storms which have been fatal to so many.
I think we have always something or other stirring us up to gratitude and love,
not only in these outward mercies,
but in the more immediate and inward tokens of His love, which are incomprehensible,
when He, whom the heaven of heavens cannot contain,
condescends to dwell in the hearts of the meanest of His poor despised people.
You, my dear Judith, seem in a great degree to enjoy the love of our dear Redeemer;
it is a most peculiar mercy to have your heart and affections,
especially at so young an age, so firmly attached to Him:
He only could preserve you in the midst of so many trials, and I doubt not,
He will still watch over you with an eye of love;
and preserve you unto His heavenly kingdom: and may you and I, my dearest Judith,
devote our lives to Him whose gifts they are, and finish our course with joy,
being ready to meet our Lord at any hour that He shall please to call.

[.centered]
=== LETTER VIII.

[.letter-heading]
To her sister Judith.

[.signed-section-context-open]
Nov. 21, 1795.

Though I am sure I can never feel half gratitude enough to my condescending redeemer,
for his great goodness, in bearing so long with me, yet glory be to his name,
that I can say, with truth; Lord, thou knowest all things, thou knowest that I love thee;
whom have I in heaven but thee,
and there is none upon earth I desire in comparison of thee: at least I think so,
and hope there is no fear of my being mistaken.
O may he preserve me, and I need not fear what man can do to me:
I do expect troubles for following Him, but do not fear them, as he has said,
"`My grace is sufficient for thee,`" and remembering that we suffer for His sake,
happy are we, for the spirit of glory and of God resteth on us.
I think I would not wish to shun so glorious a cross.
The bible, my beloved Judith, is only our outward rule,
and is no doubt the book of books, but there is "`a more sure word of prophecy,
whereunto we do well that we take heed,
as unto a light that shineth in a dark place:`" this
we may have without a word being said outwardly,
and is to be found by retiring into the temple of God, which we are; as He saith,
ye are the temples of the Holy Ghost;
and there He will not fail to manifest Himself unto us, as He doth not unto the world;
for He is not in the boisterous wind, nor in the earthquake,
but in the small still voice;
and though we can receive more comfort in thus waiting upon him in outward silence,
yet He does not refuse it to us when we are engaged in business,
as we turn our minds inward and seek his direction, even with an aspiration;
we shall feel our doubts vanish and our souls strengthened,
and be enabled to follow our dear Lord whithersoever He goeth;
this is what the prophet meant when he said, "`Eye hath not seen,
nor ear heard beside thee, O God,
what thou hast prepared for him that waiteth upon thee:`" in short,
there are more promises made to quietly waiting than any other duty.
"`They that wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles, they shall run and not be weary,
they shall walk and not faint.`"
The Psalms are full of the same: and I can say from certain experience,
that I have received more happiness from this waiting on my heavenly Father,
than I can express with pen and ink.
One night when doubting on my not receiving an immediate answer that my sins were forgiven,
and fearing they separated me from Him,
these words were in the strongest manner sweetly applied to my soul;
"`I have blotted out thy transgressions, and as a thick cloud thy sins.`"

Try this method, and may you feel the comfort of it.

[.centered]
=== LETTER IX.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
Jan. 11, 1796.

Sincerely do I sympathise with my dearest Judith,
in her very unpleasant and trying situation; but you have this comfort,
that whom the Lord loveth He chasteneth,
and that it is when He brings us into the low valley of humiliation,
He gives us of His best cordials; it is then He brings us into his banqueting house,
and His banner over us is love: and, fear not, my dear sister,
for you will be delivered from all your adversaries, inward as well as outward;
they will, I trust, rather be of use to you,
and draw you still nearer to Him in whom are hid all the treasures of the God-head bodily.
I would caution you, my love,
from imbibing from your favourite Hervey the idea of imputed righteousness; remember,
"`without holiness no man can see the Lord.`"
If actual holiness is not expected, of what use was our Lord`'s sermon on the mount,
when he says, "`Not every one that saith Lord, Lord, shall enter the kingdom of heaven,
but he that doth the will of my Father who is in heaven?`"
for not to the willing only, but to the obedient is the promise made.
He says in another place,
"`Ye are my friends if ye do whatsoever I command you:`" "`If ye know these things,
happy are ye if ye do them;`" for "`ye shall know the truth,
and the truth shall make you free,`" and if the Son therefore shall make you free,
ye shall be free indeed!
What is He to free us from!
He is called Jesus, for He is to save his people from their sins.
I fear it is a very dangerous belief,
and makes some too secure in what is nowhere promised,
that it is not possible for them to fall off, making them too easy and careless,
not considering, that He did not come to save his people in their sins,
but from their sins, that they are to take up their cross daily, and follow Him,
and that not imaginary, but real holiness, is what He meant when he said,
"`Be ye holy for I am holy:`" but think not, my Judith,
that I mean that our works can save us, for very far be such a thought from me;
for in us, that is in our flesh, dwelleth no good thing,
but we must take care to distinguish between those
works wrought in our wills and those wrought in us,
by Him who condescends to dwell in us, and makes the hearts of his people his temple.

The life of a Christian must be a continual warfare;
there must be a perpetual variance between the old man and the new;
but blessed be the name of the Lord,
He will never withhold his gracious assistance from those
who seek direction and strength from Himself only.
My mother has, I believe,
told you how much mistaken you were when you thought we were enjoying peace and quietness:
our portion outwardly is very different; but glory be to Him,
we have a comfort and happiness that the world knows not of,
and that it can neither give nor take away.
How do I pity those, little do they know what they lose,
who are pursuing vain phantoms that elude their grasp,
and only lead them farther on in the path of error and vanity,
and make their way back (if ever they return) more difficult.
I long much to see you and enjoy your much loved society:
O may you be kept as in the hollow of the great Shepherd`'s hand,
and be led forth beside the waters of comfort, and be brought to us safe,
that we may altogether feed beside the Shepherd`'s tent,
and may know Him to be our teacher and never-failing friend in every time of trouble.

[.centered]
=== LETTER X.

[.letter-heading]
To her Sister Elizabeth.

[.signed-section-context-open]
May 18, 1796,

Knowing what anxiety my dearest Eliza is in, until she hears from us,
I cannot be easy without telling her,
we are all as well as she can expect after so recent a wound.^
footnote:[This letter was written just after hearing of her eldest brother`'s death;
having some short time before heard of the death of another brother,
both in foreign lands:
these circumstances are alluded to in a subsequent part of the
letter where the expression "`treble stroke`" is used.]
My beloved mother indeed suffered much in mind and body,
but has experienced the everlasting arm of Omnipotence as a refuge from the storm,
a shadow from the heat, and as a great rock in a weary land;
she is able to sit up and take nourishment, and I trust, in a little time,
will be enabled to leave her room.
I believe it will be a great alleviation to your sorrow to hear,
we have had a letter from dear; he says he is perfectly well,
and the climate is more healthy than formerly.
Oh, may he yet be spared to us, for a treble stroke would be hard to bear.
Indeed, my beloved Eliza, I have great hopes that our dear has been mercifully accepted,
and the work has been cut short in righteousness; nothing is too hard for the Almighty,
and he had a good heart, and has, I have reason to believe,
at times felt the drawings of divine love in his soul:
my dearest parent has the consolation to think she told
him sufficient to ease her heart on religious subjects.

For all our sakes, my dearest Eliza, take care of thyself;
outward comforters avail but little,
but in retirement and silent waiting upon the Lord strength is to be renewed:
in quietness and confidence shall be thy strength,
it is only in silence that the inspeaking small still voice is to be heard;
for the Lord is not in the whirlwind, but in the small still voice:
this I believe appears strange to you, as it did to me at first; but, Oh,
try for yourself.

Taste and see that the Lord is good.
My dearest Eliza, I can write no more, but that we all unitedly,
in the bonds of gospel love, desire,
that you and my dear aunt may be kept in that peace that passeth all understanding,
and which those only can enjoy whose minds are stayed upon the Prince of Peace.

[.centered]
=== LETTER XI.

[.letter-heading]
To her Sister Judith.

[.signed-section-context-open]
8th Month 11th, 1796.

In a measure of that love which many waters cannot quench,
nor the floods of affliction drown, do I salute thee; though absent in the body,
yet as present in the Lord, in whom all his members by joints and bands,
having nourishment ministered, and knit together, increase with the measure of God.
O, my beloved sister!
What a privilege is it to feel the uniting influence of gospel love,
supporting and strengthening us, and enabling us to bear each other`'s burdens,
and so fulfill the law of Christ; this is the law of love,
which some times brings me into suffering with thee,
as being myself also bound with thee in those testimonies of Jesus,
which must be very trying to thee,
and my desires are for thee to the God of all our mercies, that He will preserve, keep,
and watch over thee for good,
and that He will favour thee and me with a knowledge of His will,
and with ability to do it.

My dearest Eliza, thou already knowest, is going, I believe, as fast as possible:
the thread is almost worn,
but her immortal soul seems fully prepared and ripe to enter into the joy of her Lord.
She does not seem (except at times) to be so sensible
of her situation as at the beginning of her illness,
when she told me she did think her sickness would be unto death,
as she seemed awakened one morning as with a person saying those words,
"`Thou shalt see the King in his beauty;`" which seemed as a message to her from heaven,
it left such a sweetness on her mind.
She is much drawn into stillness and waiting on the Lord.
She told me that some time ago, she felt desirous to be baptized in the Anabaptist way,
when she felt it clearly revealed to her that the
only baptism necessary was that of the Holy Ghost;
and that as she received that, John`'s baptism of water, she did not want;
this she told me was before she knew anything of Quakers.
Is it not an evident proof, if we wanted one,
of the tender love of our heavenly Father to His truly devoted, depending children!
How does He give them light in their dwellings; while the proud,
hard-hearted Egyptians are suffered to grope for a season, in darkness that may be felt!

Dear Eliza has not been able for this last week, to sit up longer than five o`'clock,
and this day was obliged to go to bed before one,
so thou mayest judge how her poor body is worn down:
she cannot get rest or ease from extreme pain in her chest, side, and stomach,
but by laudanum.
These dispensations must be very trying to so weak a frame as my beloved mother`'s:
May the eternal God be her never-failing refuge, and His everlasting arms be her support,
is the prayer of all that is feeling within me.
There is little in my power to do for her, as I firmly believe all her consolation is,
and must be derived from the Comforter himself.
We go to meetings, when our attendance on Eliza will admit of it.
Hannah Stephenson, a minister, sat with us, and spoke comfortably to us,
though she had a prospect of a fiery trial awaiting us beside this great one.
We look forward to what a comforting consolation it is,
that no affliction for the present appears to be joyous, but grievous,
yet afterwards it yieldeth the peaceable fruits of
holiness to those who are exercised thereby.
Give my dear love to Susan and J+++______+++,
tell them I trust to hear of their growth in grace,
and in the knowledge of our Saviour Jesus Christ;
for the right knowledge of Him is the root of immortality.

I think I may say without asking them, that my mother, aunt,
and Eliza unite in love to thee my precious Judith,
with her who feels herself doubly united to thee, both in the flesh and in the Lord,
and is thy truly affectionate sister,

[.signed-section-signature]
Lucy Ussher.

[.postscript]
====

Salute those of the household of faith that are particularly dear to me, in my name.

====

[.centered]
=== LETTER XII.

[.letter-heading]
To a Friend.

Impute not, O my endeared friend, my long silence to a want of that gratitude and love,
which fills my heart toward thee,
whenever I am capable of any feeling from the right source; but, ah,
my way has been so much in the valley of the shadow of death, that all communication,
even with thee, who at seasons seems as bone of my bone, and flesh of my flesh,
was quite cut off.
I have not found liberty to open the state of my poor tossed mind to any one;
but to thee, I believe I may say, that my soul is exceeding sorrowful even unto death:
I did hope to have seen thee,
and that thy sympathising heart would have afforded suitable instruction or reproof.
I look not for consolation or encouragement, but "`let the righteous smite me,
it shall be a kindness, and let him reprove me,
it shall be as excellent oil which shall not break my head.`"
O were I to tell thee the various plungings of my spirit,
it would far exceed the bounds of a letter;
nor do I think it would be expedient to do so,
knowing that patience must have its perfect work, and He whose name is Wonderful,
will not lay more upon me than he will enable me to bear: when I look forward,
I think my natural strength must fail if the weight
of suffering should continue much longer;
but I feel the grain of faith is mercifully afforded, though secretly,
to my drooping soul.
And shall I not leave myself in His holy hands, to do with me as he pleases?
O yes, my beloved friend, for surely I wanted emptying;
under the sense of which it has frequently been the language of my heart in times past,
O turn thy hand upon me, purely purge away my dross, and take away all my tin.
Dearly farewell.

[.signed-section-closing]
Thy truly affectionate afflicted,

[.signed-section-signature]
Lucy Ussher.
