== Extracts from Judith`'s Letters, etc.

Judith, the third sister, died of a consumption after a short confinement,
early in the year 1798, aged eighteen years and about three months.

This precious child had by nature somewhat more to subdue than her sisters,
but being daily favoured with the touches of divine truth,
and made sensible of its attractive loveliness, she hesitated not,
but gave herself up to its powerful influence,
knowing all she could do was to be as passive clay in the hand of the great Potter;
by thus submitting, the Lord in whom she delighted, worked mightily for her deliverance,
and subdued all things unto himself.--Her baptisms were deep and incommunicable;
she dwelt much in inward retirement,
and her words were few and weighty.--She bore her
last sickness with unremitted patience and meekness;
she often said, there was no cloud before her.
Two days previous to her decease, she was obliged to take to her bed,
when she sweetly said, had it been permitted,
she hoped to have been of the number of those who were not confined to bed,
that she might not give trouble.
The next morning her mental faculties were much impaired,
she seemed to lose the recollection of those about her,
until one of her brothers came into the room, when she called out, "`Oh, all is peace,
sweet peace!`"
Before her departure she seemed long engaged in supplication;
but these words only were clearly understood, "`It is all grace, free grace and mercy!`"
After which, with upraised eyes and hands,
expressed she saw an angel! when quickly her sweet spirit
took its flight to the mansions of eternal rest and peace.

She was admitted into membership with the Society
of Friends about eighteen months before her decease.

A covenant with God made by her when about thirteen years old:

O Almighty and incomprehensible Being,
I am now about to fulfill what has been long foretold by the prophet Isaiah.
One shall say I am the Lord`'s, and another shall call himself by the name of Israel,
I do here before thee this night, Oh my heavenly Father,
subscribe with my hand that I am thine; and I do,
from the bottom of my heart desire no portion but thee my God: deny,
or give me what thou pleasest, but never let me be without thee, and I shall have enough;
in thee is centered all my happiness.
I do from this moment renounce all the pomps and vanities of this false, wicked world;
but, Oh, what have I to renounce, but what would forever make me miserable!

Let angels and archangels be my witnesses,
if ever I am so base as to break this my covenant, let my name witness against me, 1793.

Judith Ussher.

LETTER I.

To Her Mother.

I much wish to be with my dearest friends, to retire oftener,
and to have more communion with my God;
that God who will never leave us if we look up to him at all times and places.
Oh that we may cleave to him with our whole heart,
that when temptations arise we may not be like the ruffled sea,
but that we may look with fresh confidence to the rock from whence we are hewn,
and receive fresh strength: may this be all our case.

LETTER II.

To Her Mother.

1795.

I rejoice that my sweet Lucy enjoys such true happiness in our dear Lord:
may she be kept by the power of God unto salvation;
may he keep her from the poisonous snares and temptations of the world.
It was He who drew us, blessed be his name,
from the yawning gulf which leads to everlasting misery, to know Him that is true,
and Jesus Christ whom He sent to perform for us, what, by reason of our sinful nature,
we could not, by thought, word, or deed, perform for ourselves;
that by faith in His perfect righteousness and meritorious death,
we may have a key to the blessed mansions of eternity.
What a delightful, but much neglected book is the bible;
how should it be valued by the children of God! in it are
promises to support us in the midst of temptations,
and under the rod of adversity,
and to keep us humble when providence with his liberal
hand disposes his favours more profusely.
May we know, at least in some degree, to value such a God, who of his great mercy has,
in this our pilgrimage, given us such innumerable, great, and valuable blessings,
that we may not only from these, but from his more immediate promises,
firmly believe that He will never leave us nor forsake us.

When I look back on my past life, and consider the great mercies of my God,
my heart exults with fearful joy; with fear, lest before I finish my course,
(knowing that in my self I am a poor weak nothing) I should in the least draw back,
for then my God would have no pleasure in me, and I could no longer call Him, my Abba.
O that my Lord may keep me from such an end; for in Him alone is my righteousness,
so in Him only have I any strength!
O may He who has begun a good work in me, never cease continuing it,
until it is perfectly completed.
May you and I, much beloved friends, when time shall be no more,
meet him that is boundless immensity,
and join those happy souls that eternally sing hallelujahs to the Lamb,
who has washed us in his blood,
and through whose most perfect righteousness we only can and will be admitted there.
My dear mother, what shall I say?
I am grieved; I tremble, for my poor +++_______+++:
O that our prayers may go up as incense before our
heavenly Father for her everlasting welfare,
that the blessed Spirit may with its enlivening influence,
draw the veil from off her understanding, and shew her, her wretched condition,
and at the same glance, a dear and dying Saviour, who will,
if she does not resist his visitations, wash her in his sacred blood:
I conclude with a line that often occurs to me,
particularly when in company with those with whom I am surrounded,

"`They build too low, who build beneath the skies,`" etc.

LETTER III.

To her Sister Elizabeth.

1795.

Will my dearest and most beloved Eliza accept of a few lines from her Judith,
who not only loves her with the strongest ties of sisterly affection, but feels,
united with it,
some of that love which the children of our heavenly Father feel for each other?
I find I am as utterly unable to do any thing for myself, towards my eternal salvation,
as a poor helpless infant; that even the thoughts of my heart are evil.
He well knew what was in man who said, the heart is desperately wicked, who can know it?
O then,
what inconceivable love was that which made our dearest
Saviour came in the form of a servant,
clothed with flesh!
He who hated the least shadow of iniquity, to bear the heavy weight of our sins upon Him!
O delightful thought, that though our sins be as scarlet,
yet washed in His most precious blood, they shall be like wool; or red as crimson,
they shall be white as snow: still, my dearest Eliza,
I want that strong witness in myself, which is promised to all God`'s children,
for which I wait with patience till his appointed time; for I have a strong hope,
that He who has begun a good work in me,
will not leave it until He has perfectly completed it.
I often think how gracious the Lord has been in drawing our poor sinful souls to Him,
who were gone astray like poor lost sheep from the
great Shepherd and Bishop of our souls;
and though the means seemed grievous at the time,
(for I am sure it was brought about by my illness) it will
teach us for the future to kiss the rod with cheerfulness,
not only without repining, but with glad hearts,
knowing that everything shall work together for good to them that love God.
I do love Him, for He first loved me,
and I would not give up the comfortable feeling of
His love for all the false pleasures of this world,
even they all united.
I feel much obliged to you and my dear aunt for your
tender concern about my going to +++_______+++,
for fear I should be drawn away by the people of this world; were I to trust to myself,
I might fear, but not more there than here.
I throw myself entirely on my heavenly Father, for of Him cometh my help:
none of us can know who may be made use of as an instrument to
draw some poor soul to think seriously of their want of a Saviour.

May we go on from grace to grace, from faith to faith,
till our bodies are laid in the peaceful grave,
and our souls are exalted to the mansions of eternal bliss,
which were prepared for us from the foundations of the world.

LETTER IV.

To Her Mother.

1795.

O my dear mother, are we not poor, weak, frail mortals in ourselves! for my part,
every day I live I feel the great depravity of my nature,
which without the interference of divine love, would forever lead me astray,
but all praise and glory be attributed to that God who has
led me to that fountain opened for sin and uncleanness,
where I may wash and be cleansed!
I long much to be with you, yet may the Almighty`'s will be done:
I have every reason to be thankful,
for His arm has been extended to preserve me unstung amidst thistles.
You who were in +++_______+++ though for a short time, must know my very unpleasant situation,
better than my pen can describe, and though this is but a small village,
its inhabitants are alike engrossed,
having their thoughts grovelling in earthly vanities,
when they know not the minute their tottering cottages may be razed,
and the unprepared possessors be compelled to quit their beloved abodes.
The Lord be praised, who though he afflicts,
does not shut up his bowels of compassion from us.
Last +++_______+++, being +++________+++`'s day for seeing company, I had more time for retirement;
and in the evening on opening my bible,
this promise in the 54th of Isaiah (with others in the same
chapter) was comfortably instilled into my soul,
"`O thou afflicted, tossed with tempests, and not comforted,
behold I will lay thy stones with fair colours, and lay thy foundations with sapphires,
etc.`"
I do everything I can that I think may be the means of drawing the hearts
of +++_______+++ to him who is ready to receive them as His adopted children,
if they will not be deaf to his kind entreaties.

I feel much for my dear +++_______+++;
may she think seriously before her precious soul takes flight into unknown regions:
may God in mercy retard it in its aged castle, until the north wind blow,
and by its powerful influence make her sensible of her wretched condition;
then may the south wind, breathing its benign influence, calm the severity of the former,
and discover a royal advocate, who is ready to do all,
the most undone sinner can want or expect!

May my dear+++________+++ also imbibe advantage by her correspondence with our beloved Eliza;
may she be convinced of her state,
and of the great peace and happiness which the sons and daughters of Jehovah enjoy:
but I rely on the mercy and power of Him who has drawn the
hearts of so many of our very undeserving family to Himself.
Have you heard any thing of our dear +++_______+++: may God keep him as he has done hitherto,
from danger,
and grant that he may yet be one of those diamonds
which compose our royal Master`'s diadem.
Some branches in the vine shoot up with great velocity,
while others with less speed advance, I trust with equal firmness:
your Judith has been one of the latter.
I acknowledge I have not as yet experienced the great
comfort of silent waiting on my dear Lord,
which you were so kind as to recommend me by experience, and by giving me a desire of it;
but consider, my dear friend, your outward tranquillity and quiet state,
while I am exposed on all sides to thistles and briars, from which,
without the aid of an invisible, but supporting arm, I could never escape unhurt;
but I must not repine, and as He who said, they should not be ashamed that wait for Him,
cannot lie, I will wait in faith.

LETTER V.

To Her Mother.

1795.

I am sorry your health still continues poorly.
I trust in the great Physician that if it be his will to afflict the body,
he will of his great and never ceasing mercy,
instil the more solid comfort into the soul, and patience to endure his chastening,
which is all sent in love.
Read from 5th to 8th verse of the 12th chapter of Hebrews, and 11th verse of ditto,
there is comfort both for you and me; may we receive it as such.
O may you and I my dear mother, go on from faith to faith, from grace to grace,
overcoming through the strength of our dear Almighty champion,
all enemies both spiritual and temporal:
though our bodies may be sore pricked with thorns and briars,
and our hearts grieved for all remaining sins,
let us with humble faith rely on the promised word for help,
remembering that he that loveth us will love us to the end, and the more he chastens,
the more strength he gives to endure, etc.

LETTER VI.

To Her Mother.

Oct.
21, 1795.

When I received your last letter my mind was eased of many uneasy fears,
which arose in it by reason of the long silence which had prevailed;
it also administered comfort to hear by it, that you enjoy the greatest of peace,
by drawing from the fountain head of bliss true and solid happiness;
which is there only to be found.

My dear mother, I am quite afraid of +++_______+++;
her whole time and attention is given up to novels; they are her study,
even before breakfast:
I asked her the other evening what she thought of people being born of the spirit;
her answer was, she never thought about it, that if she did all the good she could,
it was all that could be required of her: when I try to bring up the conversation,
she immediately evades it.
I have no hopes but in Him with whom nothing is impossible.
Every blessing attend you, even to the utmost.

LETTER VII.

To her Mother.

Nor.
5, 1795.

I think I cannot leave this till our return from +++_______+++: but protected by my dear Lord,
I shall be safe wherever his divine hand shall direct.
I have long found that we cannot always do the things that we would; but I must not,
I will not repine: the Lord`'s will be done.
What you say of dear Lucy gave me great pleasure:
may that holy Inspirer who has drawn her heart,
still keep it fixed on that object who is the most lovely among ten thousand;
and keep her disentangled from the snare of Satan and the world,
whose delusive pleasures I sincerely hope may no longer have any charms for her.
May she prefer imitating the industrious bee,
to decorating herself in the gaudy plumes of the butterfly.

We must trust almighty power for the safety of dear
+++_______+++. He who holds the winds in his fist,
and the waters in the hollow of his hand is able and I trust willing to protect him.

LETTER VIII.

To Her Mother.

Jan.
29, 1796.

I look forward with delight to the time when I may
have the company of my nearest and dearest friends.
You know not whether I may not sometimes accompany you to meetings.
Always, my beloved mother, since unrestrained by you,
you were not unacquainted with what my desires were before I left you,
which are now greatly increased.
I am not ignorant that persecution awaits me from every quarter,
from what you tell me of yourself and my dearest Lucy;
but leaning entirely on my Beloved, and armed with his strength,
though in myself entirely helpless I shall be enabled to share it with you,
and pass through this world, regardless of the gilded, but poisonous pleasures it offers,
while pity predominates in my heart for those,
who are still heedless of a superior bliss,
making my Saviour`'s will the rule of my actions,
while his blessed spirit is the guide of my ways and the directors of all my paths.

I am obliged to you for the texts you have pointed out to me; they are really delightful,
and when by faith presented to ourselves, convey true comfort;
I would add the epistle of James.

LETTER IX.

To Her Mother.

Feb.
2, 1796.

I received my dear mother`'s letter, and though I sensibly feel for your situation,
it gave me pleasure to find that your heart and affections
are so irrevocably fixed where your treasure is,
that the scornings and malicious slanders of a town, blinded by its follies,
are insufficient to shake your faith,
grounded on a foundation more lasting than the hills or mountains.
How do I pity the wretched state of our acquaintance.
My heart is depressed, and my spirits languid; methinks I hear my tender parent,
ever anxious for my welfare, requesting me to disclose to her the reasons:
consider for a while, and your momentary fears will vanish;
you that wade through such hot persecutions to attend
to the voice of our Lord wherever he calls,
must feel for one who would accompany you rejoicing,
but who is forced to act contrary to the will of her dear Master.
Am I not as one that turns aside from His flock when desired to follow their footsteps,
and to keep close to the Shepherd`'s tent?
Here I am in the midst of worldlings, when commanded to come out from among them,
and to separate myself from them.
My Sunday, which I would be happy to devote entirely to my own good,
I am obliged to spend with people who seem ignorant how to hallow it,
and to hear the sacred name continually profaned.
When that day is thus spent, you may nearly guess how the rest of the week revolves;
cards and novels, the two prevailing amusements;
the latter I am unavoidably obliged to hear, the consequence of which, not seldom,
draws a flood of tears from my eyes,
for some silly sentence too often obtruding upon my thoughts naturally prone to evil,
when I would have them fixed far above the world and its mean enjoyments:
with the Psalmist I can truly say, "`My soul longeth, yea,
even fainteth for the courts of my Lord;
my heart and my flesh cry out for the living God:
I had rather be a door-keeper in the house of my God,
than to dwell in the tents of wickedness.`"^
footnote:[I have studied the chapters my dear mother particularly mentioned,
and though personally unknown, think your new acquaintance a happy set of people.]
May you and I, my highly favoured parent,
regardless of any name by which the vain world would brand us, follow their example,
by making all our actions coincide not only with our Saviour`'s express commands,
but wherever we can discern the least indication of his will, and when we have done all,
He must be "`the Lord our righteousness.`"

LETTER X.

To Her Mother.

February 12, 1796.

I this morning received my dear mother`'s letter, which, like the preceding one`'s,
was dictated by that affection which surpasses the
fondness of a parent to the darling of her heart,
when unenforced by a stronger spiritual tie.
Your advice is always salutary, because directed by that influence which cannot err;
but be assured, my ever valued friend,
that what I cannot reconcile with the word of truth,
will be unable to influence my conduct: pardon my blunt assertion,
you have encouraged me to make it, our souls cast anchor on the same immovable,
sacred rock, and the comfortable gospel truths, are, I trust, the firm belief of us both,
besides I know not whether even in outward forms we differ;
as I have many questions to ask you on that subject, I propose deferring it till we meet.
Let the world say what they please, if the Lord will,
I am resolved I will adhere to the scriptures as far as I can discern His will;
and that where his word is simply and truly preached,
without being mixed with the doctrines of men, there I will resort;
be they ever so branded with the most infamous of names,
and esteemed the dregs and refuse of the earth.
Our blessed Lord has taught us, both by word and experience,
that we cannot serve both God and mammon,
and that a man`'s enemies are those of his own household.
I thank God, some of the principal, most beloved of mine,
are fellow travellers in the same narrow road to Zion;
but I know I have many enemies to encounter,
and having many sweet and precious promises of divine succour from above,
I will trust and not be afraid.

I have now, unembarrassed, laid before the friend of my bosom some of my real sentiments,
to whom I shall not only be ever ready,
but shall esteem it a great favour to be permitted to throw open the door of my heart,
that there unveiled you may view its contents,
being assured you will continually discover to your Judith, every thought,
whether great or small.
I look forward with great delight,
to when I need not have recourse to my pen to converse with my invaluable friends.
Remember me to +++_______+++: O that they would now in this day of salvation,
hearken to the word of life, believe its reviving truths,
and accept of the free salvation offered by the wounds of a dying Saviour,
that when they deport this life, they may fall asleep in Christ,
and awake to joys unknown!

LETTER XI.

To Her Mother.

March 2, 1796.

Next Tuesday I trust I shall be restored to friends
rendered dearer than ever by a long and painful absence,
and unspeakably precious by ties superior to those by which nature has united us: yes,
my ever valued parent,
if that God who superintends the goings of all mortals will now favour.

Yet think not I shall leave this place with out a sigh--pity strengthened
by love for those with whom I have so long lived,
has stationed itself in my heart: what words, when present could not do, may,
if aided by divine grace, be effected in a few lines.
There are many here whose blindness I pity,
while I despise the baneful pleasures they pursue.

LETTER XII.

To her Sister Elizabeth.

July 7, 1796.

Since I received your letter, my dearly beloved Eliza,
I have often felt an inclination to salute you with my pen,
and I have as many times deferred it.
Ah! is not this too often the case,
even in circumstances of far more weighty consideration,
which being from time to time delayed help to weaken the poor mind,
and at last lies dormant when, on the contrary,
if the inward monitor was immediately and implicitly obeyed,
though to try our faith it may sometimes lead us through the dark, valley,
where there is nothing to be seen on either side, yet at the end, what sweet peace,
even that which passeth natural understanding, would the tried, but obedient mind,
be favoured to enjoy!
Excuse any past deficiency, and receive this from a sister who sincerely loves you,
and who I think sensibly feels for you,
during the complicated trials with which your heavenly
Father sees meet temporally to afflict you.

Remember, my dear sister,
that though no affliction may for the present appear to be joyous but grievous,
yet at the end it yieldeth the peaceable fruits of righteousness,
unto them who are exercised thereby many are the trials and the afflictions of the righteous,
but the Lord in whom is their whole trust and dependance, will, in His own time,
deliver them out of all.
May my Eliza feel under the chastening rod of her tender Father, which is sent in love,
the great I AM`'s supporting staff secretly strengthening
and comforting her precious soul,
is the ardent but feeble breathing of my soul for you;
for He is the staff of living bread with which I believe He will feed you himself,
and give you of the living waters of the heavenly fountain to drink, in great measure,
and will never leave you nor forsake you.
I trust that seeing my beloved mother and Lucy, and their dwelling with you for a time,
will be made a means of comfort to you,
for truly I find their company salutary and delightful unto my poor mind,
which has of late been much tossed on many hidden as well as visible things,
the prospect of a separation from such truly valuable friends,
has for some time been very painful to me,
and unless a portion of inward strength is secretly handed unto my soul,
I fear I shall not part with them with that resignation
unto the divine will (by whose immediate appointment,
I believe we are thus to be separated) with which I desire to be supported,
through all the appointed or permitted trials which may fall to my share,
while passing through this tribulatory life;
and may we under every dispensation be enabled to say, "`Father, not my will,
but thine alone be done.`"

I do not wish to tire my beloved Eliza, therefore I will abridge this letter:
give my dear love to my aunt;
may you both feel that He who is the pure light of the spiritual soul,
your secret supporter and never-failing help in every time of need;
your trials may be great,
but I believe they never will exceed the strength
administered to bear them with Christian patience.
My pen would run on,
but I must retard its progress with committing you to the
care of Him who careth for you--from your unworthy sister,
who loves you more than in an affectionate manner,

Judith Ussher.

P+++.+++ S. I have, by writing you these few lines,
eased my mind of a burden with which I have been long depressed.

LETTER XIII.

To a Friend.

July 12, 1790.

I take up my pen to salute my dearly beloved friend,
who I was in hopes of seeing this day at meeting, and afterwards spending an hour with,
but from outward circumstances, and from what I can gather from inward feeling,
I shall be, I apprehend, in my place by staying this day.
Though apparently separated from you, my mind often pays you a secret visit,
and sweetly remembers the few minutes that I was favored to spend in your company,
when last in town, which were too sweet and salutary to be soon forgotten.

I could have stayed, and in the evening I scarce knew how to part.
There is much to be felt from the influence of other spirits,
which I have of late been led to consider as particularly dangerous unto me,
in my present state, and, of course, requires a continual guard over thoughts, words,
and actions.
Ah! how weak and unstable am I, to be placed in so perilous a situation;
may I then be enabled to get up into my watch tower,
and remain there during all the various vicissitudes of this wintry season;
for surely the Lord is a strong tower of defence unto the weak and weary soul,
that flies to him for refuge from its destroyers, as David did from the hand of Saul.

I have renewedly likened my present travel to the
Israelites journey through the barren wilderness,
to which my feelings incline me to believe it bears some small resemblance: but,
Ah! saith my soul, may it not through disobedience be cut off there, but pass forward,
without murmuring, and be content to dip deep in the baptizing waters of Jordan;
and even, if it is seen meet by the great Master,
that it should pass through the furnace, so that it may, be cleansed from all dross,
and the filth of the flesh, with which I feel so encumbered,
that my soul secretly mourns, and feebly breathes unto its beloved,
for the refining influence to pass over it,
that it may be fit for the Master`'s inspection,
and in due season enter the promised land.
While my fears are continually, in some measure, raised for myself; and the watchman,
as it were, sounding the alarm in mine ears, in this land of spiritual drought,
my soul is, at seasons, secretly exercised for my beloved,
+++_______+++ and +++_______+++ (who, though separate,
I think their situations pretty equal) lest the ever
watchful adversary of their soul`'s happiness,
should beguile them as he did Eve, and take the word of life out of their hearts,
and plant therein thorns and briars: Ah! that on the contrary,
they may be as engrafted branches in the heavenly vine,
bringing forth much goodly fruit to the praise and honor of Him who is the head.

I received a letter this morning, from my beloved mother;
she seemed thankful to our blessed Lord for a delightful voyage of seventeen hours;
they were then going to a little meeting, it being first day: she said,
I must not expect favorable accounts of our dear Eliza, which indeed,
from the commencement of her illness, I had but little reason to hope for,
knowing the sweet frame of her mind, I think I could, in some measure,
patiently resign her unto her dear Lord, with whom, I believe, her precious soul will,
on its exit from mortality, ever after reside, etc.

LETTER XIV.

To Her Mother.

July 15, 1796.

My dearly beloved mother`'s letter conveying the pleasing intelligence of her safety,
and my dearest Lucy, was truly acceptable unto me;
I trust you have by this concluded your journey with equal cause
for gratitude to the great unerring disposer of us unworthy worms,
may we be sensible of his favours so unmerited,
and render unto him his due tribute of grateful praise.
Ah, how sensibly am I grieved,
when my thoughts are engaged in a retrospective view of
the infinite mercy of our heavenly Father unto my soul,
in redeeming it from the bonds of Egyptian slavery,
and his condescending goodness in renewedly feeding me with such
portions of food as he sees best and most convenient for it,
still to find therein,
so much of the adamantine nature which has not yet been
penetrated by the softening rays of the sun of righteousness.
May you be preserved, my beloved mother,
through all the various trials that are in infinite wisdom allotted to you; yea,
and though you may renewedly have to pass, as through the fiery furnace, I do believe,
you will be upheld by an Almighty hand.
An inward, comfortable persuasion has attended my mind, which,
though I am fearful of mentioning,
I believe I shall not find peace in my mind unless I write it to you:
though the Lord may please to cause you to pass through the burning, fiery furnace,
and the flames so hot,
that you may be encompassed with fear lest you should
suffer in the best sense--yet fear not;
as certain as he accompanied the three children, He will be with you,
and not suffer those robes with which he has clothed you,
to be either singed or scorched by the flames.

Ah! my beloved mother, what great fear has encompassed my heart,
in communicating to you these few words, knowing how very deceitful the heart is,
lest they should have sprung from a corrupt spring;
but if I am not greatly deceived in my feelings, they were not of my own creating,
or written in my own will.
I fear you found our beloved Eliza worse, as to bodily health, than you expected,
but her precious soul, raised above the cares of the body,
and calmly resigned to the will of Him who makes all things work together for good,
to them who love and fear him.

LETTER XV.

To Her Mother.

July 23, 1796.

My beloved mother`'s letter gave me pleasure so far
as it communicated her agreeable journey,
and safe arrival at Bristol; but when I heard of the many symptoms,
which apparently threaten the approaching dissolution of our beloved Eliza,
it then contained intelligence which was truly painful,
but was not more than I was prepared for.
It is my desire to be restrained from wishing to detain
her precious soul from entering into that blissful eternity,
into which, I believe, it will undoubtedly enter, richly laden with heavenly fruit,
when time to her here shall be no more: may we each be willing,
tranquilly to resign her unto Him from whom we have received her; not only,
because she may depart,
but because it is the good pleasure of our heavenly Father to take her unto himself,
for which blessed purpose He has, in early life, prepared her immortal soul.
Though a separation from her would be a severe trial, and to you, my dear mother,
a season of renewed affliction;
yet as you are a witness to the composed tranquillity
and resignation which is apparent in her countenance,
and which by her conversation, evidently denotes her angelic frame of mind,
and readiness to depart from this state of mortality,
and enter into the undisturbed regions of eternity,
where the wicked cease from troubling, and the weary are at rest;
where "`they shall hunger no more, neither thirst any more,
neither shall the sun light on them,
nor any heat,`" but they shall be led by the "`living fountains of waters;
and God shall wipe away all tears from their eyes,`"
what consolations must these weighty considerations,
when weighed in an even balance, tend to impart to the feeling mind of my valued mother?
May the Almighty arm of divine love continually surround, support, comfort,
and strengthen you, and may you, in the day of conflicting trials,
secretly view the royal sceptre of divine approbation held forth,
encouraging your precious soul to keep above the
many waters which threaten to overwhelm it,
is the secret and renewed desire of my soul,
which feels at times so stripped and void of what is truly good,
that it is almost led to question,
whether it ever experienced the living operative power of truth at work therein:
but at other seasons, I am almost willing to believe, these are in some measure,
suggestions raised by my ever-watchful adversary; however, it has undoubtedly felt,
in a very small degree, somewhat resembling the blind man,
when he could but imperfectly distinguish "`men as trees walking:`"
may I be willing renewedly to plunge into the waters of Siloam.
Ah! how is my mind bowed down under a sense of inherent corruption,
with which it is encompassed: the language which I still use,
is become so great a weight, that at times I have remained silent,
for want of power to`" express myself; I know not whether a change therein,
will be soon or late required of me, but from what I have long felt,
I believe I shall be called on,
to use that which is most consistent with the simplicity of truth, while dwelling here.
May I, when the command goes forth, in obedience thereto,
be enabled to cast this burden at the feet of the great Shepherd of his sheep,
and humbly to wait there for such portions of strength, as He sees meet to administer.

Respecting our beloved +++_______+++,
my grandfather is perfectly satisfied that you should
have him to do as you please with him,
and bring him up in any religious society most agreeable to you; as to the nomination,
he seems quite indifferent, so that he lead an honest life.
He also wishes to have him brought up to any employment most approved of by you; he says,
he will not interfere, and desires me to say what I could to ease your mind.
Have we not, my beloved mother, abundant reason, in a feeling sense of gratitude,
to own that the Lord doth wonderfully turn the hearts of the children of men,
so as to perform his gracious purpose towards them,
who endeavour simply to follow Him in the path of truth.
I doubt not but thy heart has been already warmed with it,
in a more lively manner than words can express.

LETTER XVI.

To a Friend.

7th Month, 27th, 1796.

I think I feel as if I had made a sort of promise to my beloved friend,
that I would inform her when I heard from my dear mother respecting my precious sister.
I now sit down with an intention to forward a few lines,
hoping my past seeming deficiency,
will not be regarded as a breach of that love which I undoubtedly feel for you, and is,
I believe, all the good that springs from this heart,
unworthy the sympathy of my friends.

My dear mother and Lucy were favoured to arrive safe and well at the Hotwells,
the third evening after their landing in Milford, where they found our dear Eliza,
as bad as they could have expected: a cough attended with much pain, spitting,
night sweats, and a continual fever,
are all symptoms tending to confirm our apprehensions of its being a consumption.
My dear mother mentioned that the physicians have but little hopes,
and that she has none; but through this disease which only afflicts the body,
she carries in her countenance an angelic smile, which denotes her sweet frame of mind,
the undisturbed peace which veils it as with a mantle,
and her readiness to quit this vale of tears,
when the heavenly messenger calls her from hence into the bosom of her dear Lord.
If it is the determination of a Providence that cannot err,
to deprive us of her at this early stage of life, when youth,
and those Christian graces which are the fruits of the Spirit of God,
seem to arrive at their full bloom, may we but be resigned to the gracious will,
and supported under the chastening hand of a tender Father,
and consoled when we consider into whose care we commit her immortal soul:
for surely I believe the day`'s work is almost finished,
and that she is ripe for that eternity, into which I doubt not she is about to enter.
Oh that we may each be preserved through all the probations and
deep baptisms which necessarily attend these mortal bodies,
and be enabled to keep in our respective places,
that so when the awful errand alights at our doors,
that time to us here shall be no longer,
we may with composure look back on our past lives,
and forward with holy unintermixed joy.
While I am ready to crave that our latter days may thus close,
yet a hope scarce remains that I shall attain to such an end.
Ah! did but my beloved friend know the state of this corrupt heart, I am apt to believe,
pity rather than love, would kindle in her soul for me:
my mind has been for some time greatly depressed and brought very low,
under a feeling sense of the great depravity of my nature, which seems engrafted therein,
and, like a subtle serpent, to entwine round my inward parts.

When walking a few days ago in a garden, a lily attracted my attention;
then how did the thought sink deep into my soul,
that the soul that appears with acceptance in the presence of the Most High,
must be clad in garments as pure and white as that lovely flower.
How did I, and do I,
fear I shall never attain to the being clothed with these unspotted robes,
which I am persuaded is the beauty of the renewed soul.
Oh! when with a heart overloaded with breathings, I would look towards the mercy seat,
to be so cleansed, and washed from my great corruptions,
by that power which alone contains efficacy sufficient,
to wipe off those stains with which I am polluted,
I feel unworthy to hope for any thing from thence, and sighs are the language I utter:
Daniel`'s pathetic complaint is what my soul has adopted,
and is most expressive of my state, my comeliness is turned in me into corruption,
and I retain no strength, Being prevented from sending this yesterday,
I propose adding a few lines before I conclude.

On retiring last evening to my chamber,
and endeavouring to gather into an inward silence,
my mind was for a while involved in darkness;
when unexpectedly I felt that now was the appointed time,
in obedience to the great Shepherd,
I should no longer use that language which is far
from being agreeable to the simplicity of truth,
and which has long been, more or less, a burden almost intolerable for me to bear;
then I was desirous, that if it was the voice of truth I heard,
I might on opening the bible, meet with some passage that would confirm it,
but instead thereof, these words were impressed on my mind,
"`Blessed are they that have not seen, and yet have believed.`"
When I arose this morning the subject again opened,
and at the same time many besetting difficulties occurred,
which I knew I had not power to surmount,
unless the all supporting arm succoured me in that time of need,
and there seemed to arise a wish that the command had not yet been given,
which I hope was accompanied with a fear lest I should move before the right time:
but these, and many other words, seemed to be brought into my recollection,
"`My thoughts are not your thoughts, neither are your ways my ways.`"
"`To obey is better than sacrifice, and to hearken than the fat of rams.`"
My mind can not be sufficiently bowed down in grateful acknowledgments,
for these unmerited mercies of which I am an unworthy partaker:
Oh! that I may be enabled continually to wait in childlike
simplicity at wisdom`'s gate with mine inward ear open,
to receive her instruction, and hearken to her council;
for surely she is a tree of that life to which I feel not entitled to approach.
My dear Susan desired me to give her dear love to thee and dear +++_______+++:

In much love, I remain,

My valued friend`'s very affectionate

Judith Ussher.

LETTER XVII.

To Her Mother.

8th Month, 12th, 1796.

I received thy affectionate salutation, my beloved mother, when last in town,
wherein thou tenderly expressed thy solicitude for me,
in the promotion of my spiritual welfare.
Oh!--that it may yet prove ineffectual:
but how little do I feel of that growth and stability in the best things,
which I painfully observed thy saying, my letter gave thee pleasure to hear of:
for surely, I am apprehensive that could I lay open my heart before thee,
the various feelings of which, I may truly say, I do not myself understand,
thou would be more inclined to take up with me, a song of lamentation,
than to hope thou hast in me, a plant growing up in the garden of the Lord;
to feel myself enclosed therein, and lie, who my soul fervently desires to be unto me,
the chief among ten thousand, a wall on the right hand and on the left,
is an experience which I much wish for,
but I know myself to be unfit to be made sensible of so great a blessing.

Thou may have observed before now, an alteration which has taken place,
since my last to thee, which, I humbly trust,
was in obedience to the revealed will of the great I AM,
manifested to me in the secret of my heart, which, when I endeavoured,
though in much weakness to perform, strength was mercifully administered,
to enable me to be faithful unto the little committed unto me.
Oh! that we may, each of us,
be continually kept in the simple track of entire dedication, and perfect obedience,
for therein I am satisfied the soul is, at seasons,
favoured with a degree of that undefiled peace, which the world knows not of.
The trials and conflicts of my mind, for some time past,
have been greater than I believe it meet for me to mention, even to thee,
my beloved mother: I could almost wish to be as Elijah, hid from the world in a cave,
yet having Him for a companion, whom he alone sought for.
Solitude and retirement are what I feel most easy to myself,
if I can justly so style any situation in my present state of mind,
for the cloud that seemed to rest upon my tabernacle is departed,
my inward labour is redoubled,
and I find not that repose I vainly seek in my secret closet,
the doleful habitation of my soul.
I do mourn over my self,
being in general so deeply clad in the sable robes of spiritual night; and at times,
so remote from infinite goodness, that I much fear a state of abstractedness therefrom,
is approaching.

Oh! that I may still rely on Almighty providence, and remain wholly trusting in Him,
that though he slay me, I may fall at his feet.
I was pleased at the account thou gave me of thyself,
that (even in the midst of thy great trouble, which causes, I doubt not,
agonizing pangs to be felt at seasons,
in the prospect of a separation from our precious Eliza) thy grateful
heart is made sensible of the unfailing mercies showered down upon thee,
by an Almighty hand.

Oh! when will the day come, that I can feelingly join thee in sacred melody; for, truly,
my heart is so oppressed, that to retire from the face of visible things,
into a deserted corner of the world,
would be a situation most suitable to the barrenness of my soul;
but if it be my allotted portion to pass through
this vale of tears in the spirit of heaviness,
I desire to be content, remembering the past times,
when the fountain of life was livingly opened,
and I made sensible of its refreshing draught.
R+++.+++ J. received a letter from +++_______+++. He says,
"`Give my dear love to E. U. and precious children, who remain as living epistles,
written in my heart to this very moment: I know not that I am commissioned to say more,
than that, I believe them to be particularly under the favour of heaven;
and that He who loves his own from the beginning, loveth them unto the end,
and that he will never leave them nor forsake them.`"

Tell my beloved Lucy, with my dear love, that I think I can safely say,
that scarcely a day passes without my having her more or less in my mind; and,
though I more and more feel, as if the living fountain of life was drying up,
yet that in a dejected hour,
the remembrance of the sweet influence of her precious spirit,
is salutary and refreshing unto me.
My dear love to my beloved Eliza and aunt, in which Susan joins to thyself and Lucy,
and I remain thy unworthy, but, I think truly affectionate daughter,

Judith Ussher,

LETTER XVIII.

To her Mother.

9th Month, 9th, 1796.

Was it not my beloved mother`'s request to hear from me once a week,
it seems to me most probable, my pen would be at this time unoccupied,
and while I take it up, I am feelingly sensible of my great incapacity,
acceptably to offer thee any thing.
However, this I am persuaded, that thine and my beloved Lucy`'s consolations,
(for I think my spirit though feebly salutes you both in your very
tribulated path,) are all derived from that unadulterated fountain,
which issueth in due time unto the poor, tried, and weary soul, an inexhaustible stream.
Thy sweet letter, my valued mother, even before I opened it,
brought a peace to my poor mind, to which I am mostly a stranger:
perhaps it is this Spirit, which formerly discovered itself in the multitude,
when they followed Jesus only for the loaves and fishes, that has fastened upon me;
but I may truly say, that I am far from wishing to indulge it,
rather desiring to feel the craving appetite of the corrupt will so mortified,
as in all things entirely to give up to the turnings of the divine hand.
A fast has been however, I believe in much wisdom, dispensed, the living bread,
handed in secret, being long withheld: may we therefore,
now be preserved from kindling sparks of our own,
or endeavouring to make a substitute in the absence of our beloved; for,
I trust no sensual enjoyment, nor anything less than the immediate presence of Him,
whom we each desire to be in us, the Alpha and Omega,
can yield our souls that for which mine in secret mourneth.

Though Belial may, at such times as these,
strive to turn our hearts from the King of Israel, yet let us,
suspecting him in all our ways, turn a deaf ear to his malicious whispers,
remembering that, "`he savoureth not the things that be of God,
but those which be of man,`" because thereby his dominion is exalted:
from experience I may say, it is far from being easy, when best help is withdrawn,
to shut out the transforming enemy; it is then he works hardest,
and with most prevailing strength in the poor soul,
in blocking up the way from the entrance of the river of life:
can I but preserve an avenue for its return, I believe it will be by hard wrestling.
Could I but indulge that hope with which thou endeavours to encourage me,
that the darkness which hath been so long in my soul, is by the Lord,
suffered to be there for this blessed end, to ground and settle it in virtue;
I should not only be content, but rejoice, I think in some measure: however,
let us rest in patience the appointed season, and not add to our afflictive trials,
by an unsubjected will, but rather in all things,
give ourselves up to the forming of our heavenly Father`'s hand;
remembering we are but clay, and consequently,
ignorant of the means which may most efficaciously
tend to the purifying our earthen vessels.

While I write, I feel an unusual earnestness, that we may each be prepared and ready,
with dedicated hearts, to step forward at the call of our great Master,
in any line of duty and devotedness, however repugnant to flesh and blood,
and acquit ourselves so as to bring praise to the great and eternal name,
regardless of how much self is abased.
But from what quarter arise these sensations?
for the minute before,
I was ready to acknowledge myself destitute of any that had in them the savour of life,
it being my daily humbling; experience, to explore the path of obscurity,
being weary of myself and all visible objects.
I have wished to pass along unnoticed,
having my name blotted out of the book of remembrance, but this is not the will of Him,
who prayed not that we should be taken out of the world,
but that we should be kept from the evil of it.

The account of our precious Eliza, conveyed some comfort to me,
though she had to drink so deep of the cup of suffering,
and little likelihood of the dear body remaining much longer with you.
Bear up through all, beloved mother and sister, with Christian fortitude,
and may the arm of Omnipotence be your support; for I believe,
nothing else could carry you through so great afflictions.
I remain in that love, which at this time flows towards you,
my valued mother and sisters, more than affectionate,

Judith Ussher.

LETTER XIX.

To a Friend.

10th Month, 4th, 1795.

Thy frequent kind enquiries and many messages of love, my dear friend,
to one who not only feels unworthy regard,
but even the notice of any whose names are written in the Lamb`'s book of life,
were acceptable;
gratitude seemed before now to have prompted the
dictating a few lines in acknowledgment thereof;
however, if my long silence requires an excuse,
let the distressed situation of my poor mind plead one, when I tell thee,
that for a considerable time past it has not only been stripped of every sensible enjoyment,
(were it confined to this,
I think I should not repine) but it has almost continually
laboured under such an oppressive weight,
the burden whereof has at times, particularly of late, seemed almost insupportable;
that in the bitterness of my soul I have been forced to utter, My God, my God,
why hast thou forsaken me?--even the purest friendship,
or the society of the choicest of my beloved friends, I am incapable of enjoying;
like the pelican in the wilderness, so my soul sits mourning in every corner;
and with the prophet I have wished that I had in this wilderness a lodging-place,
that thither I might flee; but this denied,
in lieu thereof may patience be proportionably granted,
so as to keep the poor soul from quite sinking or striking on the quicksands of despair:
faith is at so low an ebb at times that it can scarcely
be compared to a grain of mustard seed,
and even that, so hid in the earth,
as often to cause the closest search to prove fruitless;
the fountain of living waters being closed in myself,
I have long rather preferred to sit mourning at the well`'s mouth,
than seek for comfort from other springs;
for I feel as if the waters from another`'s cistern could yield me no consolation:
I remain much in external and internal solitude,
and when with those dear friends under this roof, whose company I know not how to value,
I have been as it were constrained to retire;
but when with them I wish in some measure to disguise
the deep distress in which my soul is involved,
and which the band of Omnipotence only can fathom.

I knew not but that my mind might have received some
relief by writing to thee my dearly beloved friend,
but I find it too full for words to unburden;
however I hope what I have said will be a sufficient apology
for my not having handed thee before now a few lines,
particularly on the arrival of my beloved mother and sister,
who have been through infinite mercy preserved in tolerable health, though neither well;
but their kind Master, into whose hands they resigned the helm of their vessels,
while he led them through the sea of adversity,
recruiting them with needed supplies of strength and provision,
mercifully kept them within sight of the harbour of peace,
where I trust they have since measurably been enabled with
grateful praise in their hearts safely to cast anchor.
Written in much love by thy very affectionate, and, Oh! that I might add,
fellow traveller towards a city which hath foundations,

Judith Ussher.

LETTER XX.

To a Friend.

1st Month, 30th, 1797.

Little did my heart conceive when I last parted from thee my dear and valued friend,
the many and deep afflictions which awaited me, the severest of which originated within:
ah! how many months have now passed since the soul
could rejoice at the voice of its beloved,
or even distantly behold his feet upon the mountains: surely if his presence giveth life,
the withholding thereof causeth darkness and death,
then the soul that hath none in heaven but Him,
nor in all the earth it desireth beside him, can not but mourn.
Oh! then did I become a burden to myself and society:
and sorrows so increased that the pit had almost closed her mouth upon me,
when for a season, yea, a very little season,
the clouds seemed to wear a less rigorous aspect,
and in the seeming prospect of returning day,
the soul was almost ready to rejoice in hope of again embracing its beloved; but,
Ah! how hath it proved, but the presage of a more dark and stormy season,
wherein the heavens appear as brass, and the gates thereof like bars of iron,
the sun which once measurably illuminated my path has been darkened in his going forth,
and is no longer a lamp to my feet, and a light unto my paths,
and the creatures yield no consolation;
my bed seems to be made in the deep waters where the floods have overflowed my soul,
and the weeds are wrapped about my head.
In this sad desertion of Almighty goodness,
I have sought much for silence and retirement, where,
though there has been a seeking and not finding the Beloved of souls,
yet I have thought it is well to be found waiting for Him in the way of his coming:
the porter knows not at what time his Lord may come, at midnight, at the cock-crowing,
or in the morning.
I have therefore wished to be kept watchful,
if peradventure he may again remember his afflicted servant,
though hope seems almost fled.
I have, I believe, with reason, dreaded the natural impatience of my disposition,
which has been ready to conclude it vain to wait upon the Lord,
seeing he hath rejected me from among his servants,
and cast me from his presence as a reprobate branch;
yet there has been a struggle for resignation, which has at seasons been so far attained,
as to cause a language similar to this, "`though he slay me, yet will I trust in him.`"

Ah! my dear friend, hard would it be to relate the deep distress,
through which this poor soul has waded, and in which it continues plunged.
Though I find I have mentioned more than I intended,
and almost chide myself causing thee thereby to partake of my sufferings,
yet I write not to give pain; no, but feeling myself desolate and forlorn,
the billows daily rising higher,
and the inhabitant of this earthly tabernacle almost wallowed by the overflowing surges;
I thought to write thee a few lines, (knowing thee to be a father in Israel,
and encouraged thereto by thy writing to my beloved mother) that
if such a poor worthless worm was still retained in remembrance,
perhaps the moment might arrive, wherein she who cannot plead for herself,
might be pleaded for at the footstool of mercy, that faith and patience fail not,

Judith Ussher.

* * *

Susanna, the youngest sister died of a consumption, early in the year 1798,
aged nearly fifteen years.

This dear child was sweetly taught in the school of her dear Lord;
she was drawn into great simplicity, and evinced that truth leads into plainness.
Her bodily sufferings were great,
but He who thus was pleased to carry on the work of purification, supported her.

A few days, (if not the day) before her final removal, being with her mother,
she expressed nearly this language: "`Mother, I am not afraid to die,
but feel comforted to be taken from the evil to come,
which probably I should not have power to resist.`"

In a letter to her mother when at Bristol, is the following paragraph:
"`I am sure thine and dear Lucy`'s sufferings on dear Eliza`'s account are very,
very great,
but I believe the Lord in his great mercy will support
all those that trust in Him alone.`"

The following lines were found among her papers, written in her own hand:--

Many are the trials and the conflicts the spiritual mind has to sustain,
before it can enter the promised hind, but if it endure to the end,
it shall obtain the prize.

The foundation of God standeth sure, having this precious and unbroken seal,
"`The Lord knoweth them that are his.`"
Strive man fully to enter into the strait gate,
for many are the hindrances and besetments with which the
adversary of the soul`'s happiness will invade it,
and endeavour to turn it into the broad road of eternal destruction.

O bring more and more of thy children under thy yoke; make them think thy yoke easy,
and thy burden light; make them follow thee and thy faithful ones forever and ever.
Have mercy and forgive the sins of thy children, and the out-steppings of thy chosen ones.
Encourage, O Lord, I beseech thee, them that are heavy laden,
help them through the waters of affliction,
support them over all that it is thy will to put upon them:
Thou wilt have mercy and not sacrifice: Thou wilt have compassion on the children of men;
O look down with compassion upon them, for thou art merciful, long-suffering,
patient in mercy!

FINIS.
