== A Short Memorial of Elizabeth Ussher

Elizabeth Ussher, daughter of William and Mary Paul, was born in Waterford,
on the 22nd of 5th month, 1749.
Her father was an opulent alderman of that city, and the sphere in which she moved,
alluringly invited her to indulge in worldly pleasures;
yet she was early inclined to seriousness,
and frequently felt the sting of compunction in pursuing
those gratifications which by many are deemed innocent,
but which she found incompatible with christian self-denial.
She was educated a member of the Church of England,
and in sincerity of heart strictly conformed to the ordinances of that profession;
yet in recounting the merciful dealings of her Saviour, whom she sought to serve,
she gratefully acknowledged that her mind was often attracted, in silent meditation,
to an acquaintance with that Divine principle which she was afterwards favoured to know,
and embrace, more perfectly.

In 1770 she married John Ussher, of Coppagh, County of Waterford.
After a union of seventeen years with her beloved husband,
a series of severe family afflictions fell to her lot--she was left a widow,
and was deprived of her two elder sons, by death on a foreign shore,
far from her maternal care and kindness.
Under these trials her mind was more powerfully awakened to see that the path
cast up for her must be narrower than that in which she had hitherto walked;
during this state of mental exercise, at the close of the year 1796,
she was summoned to England to attend her eldest daughter, Elizabeth,
in her last illness, and who had resided for several years at Bristol with her aunt,
a sincere christian, whose influence had had a happy effect upon her pious mind,
and she died in great peace.

On her return to Waterford after her daughter`'s death,
Elizabeth Ussher formed an acquaintance with some members of the Society of Friends.
The dejection occasioned by her recent trials,
caused her to decline entering much into company,
and the serious conversation and manners of her new associates were in
harmony with the state of her spirits and her religious feelings.
She attended their meetings, as did her three remaining daughters, Lucy, Judith,
and Susanna, and being convinced of the principles of truth as professed by Friends,
they were all received into that society as members in the
year 1797;--the fruits of their unreserved obedience to
the heavenly visitation were evinced in retiredness of mind,
christian simplicity,
and that humble and steady deportment which denoted
the prevalence of a meek and quiet spirit;
so that a friend who occasionally visited them, remarked,
that the sweet feeling pervading the family, seemed like a foretaste of Heaven.

This consoling display of Divine power was succeeded by repeated trying dispensations,
for within the short space of five months their gracious Lord,
who had so abundantly manifested His love to those precious plants,
saw meet to remove them beyond the reach of temptation and sorrow; young in years, yet,
it is believed, prepared through faith in Christ Jesus,
for admission into the kingdom of heaven.

In all these and many other conflicts Elizabeth Ussher`'s
submission to the chastening of her heavenly Father,
evinced that she was divinely succoured,
and her patience supplied from the source of unfailing mercy.
This she often commemorated as a special favour from her Lord,
whom she was made willing to leave all, and resign all, to love and follow.

She was accustomed to keep an occasional diary, from which the following memoranda,
referring to her children, are extracted.

11th month, 21st, 1797.
"`My beloved Lucy departed this life between four and five o`'clock in the evening,
and her sweet, meek spirit, fitted for her beloved Lord, by deep and purifying baptisms,
was released from a state of trial and suffering to one of glory, to be forever with Him,
whom her soul loved, and whom she followed through evil report, and good report.
Despising the shame and the dreaded scoff of man, she steadily looked to Him,
who she saw was altogether lovely,
until, from seeing Him as through the glass of mortality,
she is gone to His presence where is '`fulness of joy.`'`"

12th month, 29th, (alluding to Judith.) "`Her sweet purified spirit,
having bowed to the will of her heavenly Father,
he has been pleased to cut short the work in righteousness.
He has set his love upon her, and she is his.
He has prepared for her a crown of glory that fades not away,
to which inheritence she is hourly hastening.
'`O! dearest Father, I have no doubt that what you are doing in thus afflicting,
in a manner so uncommon is in unerring wisdom,
surely these dear girls were never so precious to me,
as since their hearts were devoted to You, it was in You we were united,
and my love increased with their love to You.`'`"

1st month, 9th, 1798.
"`At half past seven this evening, my beloved Judith was taken to glory;
nearly seven weeks after her dear sister,
she had to express "`All is peace! sweet peace!`"
If my precious children have left me they are gone to our beloved Lord,
and surely he is worthy of every sacrifice.
O! yes, inexpressibly worthy is the Lord of my affections, of all that he gave,
and his love repays for all.`"

3rd month, 8th. "`At a quarter past two o`'clock in the afternoon,
it pleased my dear Lord to take my precious Susan,
the last of all my daughters to himself.
This, to human nature seemed to be the crucifying power, and the poor,
tried creature had no doubt fallen in the conflict,
had not the everlasting arms been underneath to support and comfort.
* * * I have great cause to say that all anguish
was lost in the brightness of divine goodness.`"

Keenly as her affectionate heart felt the separation from the tender objects of her care,
she did not oppress her friends with her sorrows; she walked calmly on her way.
Her manners were marked by native courtesy,
and the polish of a liberal and polite education:
yet they were still more remarkable for simplicity and deep humility.
She dreaded the approach of any thing which might lead from these in herself or others;
and her solicitude was fervent, that all might be preserved on the true foundation.
She believed it was required of her to preach the gospel, and in the year 1806,
was acknowledged by the Society of Friends as a minister; on this occasion she writes,
"`this day my name was recorded as a minister of the everlasting gospel.
"`O!`" saith my soul, '`may it be recorded in the Lamb`'s book of life,
and never may it be blotted out.`"
She travelled with a certificate in visiting the meetings of Friends in London,
and some other meetings in England,
and once united in a family visit to Friends of Waterford.
Her heart expanded with universal love, and towards such as she believed had,
in any degree, yielded to the humbling power of true religion,
it flowed in a current of earnest desire for their growth and establishment therein.

During an illness of some months`' continuance,
she appeared to be quietly waiting the disposal of her divine master,
and referring all to his will;
desirous to be detached from everything tending to
disturb the abstracted dependance on him,
wherein she found her strength consisted; and which centered her mind in love,
and enabled her, in a retrospect of the tribulations she had been sustained under,
the mercies re ceived, and the work that had been done in her, to say,
in humble gratitude, "`My Redeemer has done all for me, and to him be the glory!`"

She departed this life, the 27th of 4th Month, 1817, aged nearly Sixty-eight years.
